#!/usr/bin/env bash
# Generate an extension upgrade script.
#
#   scripts/gen-upgrade.sh 0.1.0 0.2.0
#
# sql/control_plane.sql, sql/operator_agents_and_policies.sql,
# sql/operator_runtime_and_integrations.sql, sql/operator_accounts_and_chat.sql,
# sql/seed_data.sql, sql/selftest.sql, and sql/grants_and_facade.sql (split
# out of what used to be one file -- KNOWN_ISSUES.md item 38 -- but always
# applied together, in that exact order: src/lib.rs's extension_sql_file!
# `requires` chain enforces the same order fresh-install uses) are written
# to be idempotent -- CREATE OR REPLACE, IF NOT EXISTS, ON CONFLICT DO
# NOTHING, create-only seeds, and explicit DROPs for anything whose
# signature or return type changed -- so replaying all seven is a valid
# upgrade path.  This script is what makes that an actual, versioned file
# rather than an assumption.
#
# These seven files only ever hold hand-written SQL (tables, PL/pgSQL
# functions, views): a native function declared in src/lib.rs via
# `#[pg_extern]` (e.g. allgres.native_host_stats) is not in it at all --
# pgrx generates that function's `CREATE FUNCTION ... LANGUAGE c` statement
# itself and splices it into the *fresh-install* file
# (allgres--<to>.sql) only. A hand-dumped upgrade script that skipped this
# would leave a brand-new native function missing after `ALTER EXTENSION
# ... UPDATE TO` on any database that predates it -- confirmed live once
# (item 44's native_host_stats): `overview` failed with "function
# allgres.native_host_stats() does not exist" on an upgraded database
# despite passing on every fresh install, because fn_selftest itself is
# hand-written SQL and upgraded correctly while the native function it
# calls did not. Fixed by extracting every native (`LANGUAGE c`) function
# declaration pgrx just generated and prepending it here too, rewritten as
# CREATE OR REPLACE so it is idempotent against a target that already has
# an older (or, for one that predates this fix, no) version of it.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <from-version> <to-version>" >&2
  exit 2
fi

from="$1"
to="$2"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/sql/allgres--$from--$to.sql"

fresh=""
if command -v pg_config >/dev/null 2>&1; then
  sharedir="$(pg_config --sharedir 2>/dev/null || true)"
  if [[ -n "$sharedir" && -f "$sharedir/extension/allgres--$to.sql" ]]; then
    fresh="$sharedir/extension/allgres--$to.sql"
  fi
fi

{
  echo "-- Allgres $from -> $to."
  echo "-- Generated by scripts/gen-upgrade.sh from sql/control_plane.sql,"
  echo "-- sql/operator_agents_and_policies.sql,"
  echo "-- sql/operator_runtime_and_integrations.sql,"
  echo "-- sql/operator_accounts_and_chat.sql, sql/seed_data.sql,"
  echo "-- sql/selftest.sql, and sql/grants_and_facade.sql; do not edit."
  echo "-- Applied with: ALTER EXTENSION allgres UPDATE TO '$to';"
  echo

  if [[ -n "$fresh" ]]; then
    echo "-- Native (Rust, \`#[pg_extern]\`) function declarations, extracted from"
    echo "-- the fresh-install file pgrx just generated ($fresh) and"
    echo "-- rewritten as CREATE OR REPLACE -- see this script's own header comment."
    awk '
      /^CREATE  FUNCTION / { capture=1; stmt=$0; is_native=0; next }
      capture {
        stmt = stmt "\n" $0
        if ($0 ~ /LANGUAGE c( |$)/) is_native=1
      }
      capture && /;$/ {
        if (is_native) {
          sub(/^CREATE  FUNCTION/, "CREATE OR REPLACE FUNCTION", stmt)
          print stmt
          print ""
        }
        capture=0
      }
    ' "$fresh"
  else
    echo "-- NOTE: could not locate the fresh-install file for $to (build it first" \
         "with cargo pgrx install, then re-run this script) -- any native" \
         "(#[pg_extern]) function added since $from is NOT included below." \
         "Verify with a real ALTER EXTENSION ... UPDATE TO '$to' before releasing." >&2
  fi

  cat "$root/sql/control_plane.sql" \
      "$root/sql/operator_agents_and_policies.sql" \
      "$root/sql/operator_runtime_and_integrations.sql" \
      "$root/sql/operator_accounts_and_chat.sql" \
      "$root/sql/seed_data.sql" \
      "$root/sql/selftest.sql" \
      "$root/sql/grants_and_facade.sql"
} > "$out"

echo "wrote $out"
