#!/usr/bin/env bash
# Generate an extension upgrade script.
#
#   scripts/gen-upgrade.sh 0.1.0 0.2.0
#
# sql/control_plane.sql is written to be idempotent -- CREATE OR REPLACE,
# IF NOT EXISTS, ON CONFLICT DO NOTHING, create-only seeds, and explicit DROPs
# for anything whose signature or return type changed -- so replaying it is a
# valid upgrade path.  This script is what makes that an actual, versioned file
# rather than an assumption.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <from-version> <to-version>" >&2
  exit 2
fi

from="$1"
to="$2"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/sql/allgres--$from--$to.sql"

{
  echo "-- Allgres $from -> $to."
  echo "-- Generated by scripts/gen-upgrade.sh from sql/control_plane.sql; do not edit."
  echo "-- Applied with: ALTER EXTENSION allgres UPDATE TO '$to';"
  echo
  cat "$root/sql/control_plane.sql"
} > "$out"

echo "wrote $out"
