-- Allgres 0.1.0 -> 0.2.0.
-- Generated by scripts/gen-upgrade.sh from sql/control_plane.sql; do not edit.
-- Applied with: ALTER EXTENSION allgres UPDATE TO '0.2.0';

-- Allgres 0.2.0 control plane.
--
-- Internal argo_* schema names are intentionally retained for upgrade compatibility.
-- User-facing native functions are exposed under schema allgres.
--
-- This file is the single canonical definition of the control plane.  Every
-- object is defined exactly once, in dependency order; there are no superseded
-- copies left behind by earlier migrations.  The file is idempotent, so it can
-- be replayed as an `ALTER EXTENSION ... UPDATE` script (see scripts/gen-upgrade.sh).
--
-- Layout:
--   1. roles
--   2. schemas, tables, indexes, triggers
--   3. generic helpers
--   4. outbound URL / host guards      (shared by the LLM and tool paths)
--   5. provider secret storage
--   6. SQL sandbox                     (fn_execute_sql and its parser)
--   7. agent state machine             (fn_next_step / fn_submit_result)
--   8. pump                            (dispatch / claim / complete / watchdog)
--   9. operator API
--  10. seed data
--  11. selftest
--  12. grants
--  13. allgres facade + dashboard RPC

-- ---------------------------------------------------------------------------
-- 1. Roles.  Invariant 7: three runtime roles.  argo_owner is deploy-only.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'argo_owner') THEN
    CREATE ROLE argo_owner LOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'operator') THEN
    CREATE ROLE operator LOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'worker') THEN
    CREATE ROLE worker LOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sandbox') THEN
    CREATE ROLE sandbox NOLOGIN;
  END IF;
END
$$;

-- The sandbox never resolves an unqualified relation name: fn_execute_sql
-- narrows search_path to pg_temp before running model-generated SQL, and this
-- default keeps that true for any other session that assumes the role.
ALTER ROLE sandbox  SET search_path = pg_temp;
ALTER ROLE worker   SET search_path = argo_public, pg_temp;
ALTER ROLE operator SET search_path = argo_private, argo_public, pg_temp;

-- The runtime worker drops to `worker` per transaction and fn_execute_sql then
-- drops further to `sandbox`; that second hop needs role membership.
GRANT sandbox TO worker;

-- ---------------------------------------------------------------------------
-- Drop objects whose signature or return type changed since 0.1.0.
-- CREATE OR REPLACE cannot do either, so upgrades need an explicit drop.
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS argo_public.fn_set_provider(uuid, text, boolean, text, text, text, text);
DROP FUNCTION IF EXISTS allgres.create_session(uuid, text);

-- The SQL sandbox no longer inspects statement text with regexes; it reads the
-- tree produced by PostgreSQL's own parser (allgres.analyze_sql).  These are
-- the hand-rolled lexer that replaced.
DROP FUNCTION IF EXISTS argo_private.sql_table_refs(text);
DROP FUNCTION IF EXISTS argo_private.sql_relation_refs(text);
DROP FUNCTION IF EXISTS argo_private.sql_cte_names(text);
DROP FUNCTION IF EXISTS argo_private.sql_normalize(text);
DROP FUNCTION IF EXISTS argo_private.strip_sql_noise(text);

-- ---------------------------------------------------------------------------
-- 2. Schemas, tables, indexes, triggers.
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS argo_private;
CREATE SCHEMA IF NOT EXISTS argo_public;

CREATE TABLE IF NOT EXISTS argo_private.agents (
  agent_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL UNIQUE,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS argo_private.policies (
  agent_id        uuid PRIMARY KEY REFERENCES argo_private.agents(agent_id) ON DELETE CASCADE,
  system_prompt   text NOT NULL,
  max_steps       int NOT NULL DEFAULT 20 CHECK (max_steps > 0),
  max_retries     int NOT NULL DEFAULT 2 CHECK (max_retries >= 0),
  llm_config      jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS argo_private.permissions (
  permission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id      uuid NOT NULL REFERENCES argo_private.agents(agent_id) ON DELETE CASCADE,
  resource_type text NOT NULL CHECK (resource_type IN ('view', 'tool', 'agent', 'http_host')),
  resource_ref  text NOT NULL,
  granted_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (agent_id, resource_type, resource_ref)
);

CREATE TABLE IF NOT EXISTS argo_private.sql_sandbox_allowlist (
  resource_ref text PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS argo_private.sessions (
  session_id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id      uuid NOT NULL REFERENCES argo_private.agents(agent_id),
  goal          text NOT NULL,
  status        text NOT NULL CHECK (status IN ('open', 'completed', 'failed', 'cancelled')),
  final_answer  text,
  started_at    timestamptz NOT NULL DEFAULT now(),
  completed_at  timestamptz
);

CREATE TABLE IF NOT EXISTS argo_private.tasks (
  task_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      uuid NOT NULL REFERENCES argo_private.sessions(session_id),
  agent_id        uuid NOT NULL REFERENCES argo_private.agents(agent_id),
  parent_task_id  uuid REFERENCES argo_private.tasks(task_id),
  status          text NOT NULL CHECK (status IN
                    ('queued', 'running', 'completed', 'failed', 'waiting_human')),
  step_count      int NOT NULL DEFAULT 0,
  input           jsonb NOT NULL DEFAULT '{}'::jsonb,
  output          jsonb,
  error           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tasks_ready_idx
  ON argo_private.tasks (created_at)
  WHERE status IN ('queued', 'running');
CREATE INDEX IF NOT EXISTS tasks_session_idx
  ON argo_private.tasks (session_id, created_at);
CREATE INDEX IF NOT EXISTS tasks_agent_status_idx
  ON argo_private.tasks (agent_id, status);
CREATE INDEX IF NOT EXISTS tasks_updated_idx
  ON argo_private.tasks (updated_at DESC);

CREATE TABLE IF NOT EXISTS argo_private.execution_logs (
  log_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id     uuid NOT NULL REFERENCES argo_private.tasks(task_id),
  step_number int NOT NULL,
  role        text NOT NULL CHECK (role IN
                ('system', 'user', 'assistant', 'tool', 'error', 'operator')),
  content     jsonb NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS execution_logs_task_idx
  ON argo_private.execution_logs (task_id, step_number, created_at);
CREATE INDEX IF NOT EXISTS execution_logs_created_idx
  ON argo_private.execution_logs (created_at DESC);

CREATE TABLE IF NOT EXISTS argo_private.human_approvals (
  approval_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id     uuid NOT NULL REFERENCES argo_private.tasks(task_id),
  status      text NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
  payload     jsonb NOT NULL,
  decided_at  timestamptz
);

CREATE TABLE IF NOT EXISTS argo_private.llm_providers (
  provider_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name            text NOT NULL UNIQUE,
  kind            text NOT NULL CHECK (kind IN ('openai_compat', 'anthropic', 'oauth')),
  base_url        text NOT NULL,
  oauth_auth_url  text,
  oauth_token_url text,
  oauth_scope     text,
  oauth_client_id text,
  is_enabled      boolean NOT NULL DEFAULT true,
  -- Opt-in escape hatch for loopback / RFC1918 endpoints (Ollama, LM Studio,
  -- an in-cluster gateway).  Without it the outbound guard rejects them, which
  -- is what stops a dashboard user from turning the LLM path into an SSRF.
  allow_private_network boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE argo_private.llm_providers
  ADD COLUMN IF NOT EXISTS allow_private_network boolean NOT NULL DEFAULT false;

-- Never returned by list functions.  Operator writes via fn_set_provider_secret.
CREATE TABLE IF NOT EXISTS argo_private.llm_secrets (
  provider_id         uuid PRIMARY KEY REFERENCES argo_private.llm_providers(provider_id) ON DELETE CASCADE,
  api_key             text,
  oauth_client_secret text,
  access_token        text,
  refresh_token       text,
  expires_at          timestamptz
);

CREATE TABLE IF NOT EXISTS argo_private.oauth_states (
  state        text PRIMARY KEY,
  provider_id  uuid NOT NULL REFERENCES argo_private.llm_providers(provider_id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS argo_private.outbound_calls (
  call_id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id          uuid NOT NULL REFERENCES argo_private.tasks(task_id),
  kind             text NOT NULL CHECK (kind IN ('llm', 'tool')),
  tool             text,
  url              text NOT NULL,
  request_headers  jsonb NOT NULL DEFAULT '{}'::jsonb,
  request_body     jsonb NOT NULL DEFAULT '{}'::jsonb,
  net_request_id   bigint,
  status           text NOT NULL CHECK (status IN ('queued', 'in_flight', 'harvested', 'lost')),
  response_status  int,
  response_body    text,
  error            text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS outbound_ready_idx
  ON argo_private.outbound_calls (created_at)
  WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS outbound_task_idx
  ON argo_private.outbound_calls (task_id, status);
CREATE INDEX IF NOT EXISTS outbound_inflight_idx
  ON argo_private.outbound_calls (updated_at)
  WHERE status = 'in_flight';

CREATE TABLE IF NOT EXISTS argo_private.demo_sales (
  sale_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id  uuid REFERENCES argo_private.agents(agent_id) ON DELETE CASCADE,
  region    text NOT NULL,
  sku       text NOT NULL,
  amount    numeric NOT NULL,
  sold_on   date NOT NULL
);

CREATE OR REPLACE FUNCTION argo_private.current_agent_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $fn$
  SELECT nullif(current_setting('argo.agent_id', true), '')::uuid
$fn$;

CREATE OR REPLACE FUNCTION argo_private.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS agents_touch ON argo_private.agents;
CREATE TRIGGER agents_touch
  BEFORE UPDATE ON argo_private.agents
  FOR EACH ROW EXECUTE FUNCTION argo_private.touch_updated_at();

DROP TRIGGER IF EXISTS tasks_touch ON argo_private.tasks;
CREATE TRIGGER tasks_touch
  BEFORE UPDATE ON argo_private.tasks
  FOR EACH ROW EXECUTE FUNCTION argo_private.touch_updated_at();

CREATE OR REPLACE FUNCTION argo_private.forbid_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  RAISE EXCEPTION 'execution_logs are append-only'
    USING ERRCODE = 'P0001';
END;
$fn$;

DROP TRIGGER IF EXISTS execution_logs_no_update ON argo_private.execution_logs;
CREATE TRIGGER execution_logs_no_update
  BEFORE UPDATE OR DELETE ON argo_private.execution_logs
  FOR EACH ROW EXECUTE FUNCTION argo_private.forbid_log_mutation();

CREATE OR REPLACE FUNCTION argo_private.ensure_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  INSERT INTO argo_private.policies (agent_id, system_prompt, llm_config)
  VALUES (
    NEW.agent_id,
    $prompt$You are an agent whose next action is decided only as JSON.
Reply with a single JSON object, no markdown, no extra keys:
{"action":"final_answer","answer":"..."}
{"action":"execute_sql","sql":"SELECT ..."}
{"action":"call_tool","tool":"...","args":{}}
{"action":"delegate","agent_name":"...","input":{}}
{"action":"await_human","reason":"..."}
SQL must be a single SELECT or WITH against schema-qualified views you were given.
$prompt$,
    jsonb_build_object(
      'provider', 'xai',
      'model', 'grok-4.5',
      'temperature', 0.2,
      'max_tokens', 1024
    )
  )
  ON CONFLICT (agent_id) DO NOTHING;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS agents_ensure_policy ON argo_private.agents;
CREATE TRIGGER agents_ensure_policy
  AFTER INSERT ON argo_private.agents
  FOR EACH ROW EXECUTE FUNCTION argo_private.ensure_policy();

-- ---------------------------------------------------------------------------
-- 3. Generic helpers.
-- ---------------------------------------------------------------------------

-- base_url is deliberately NOT accepted here.  Per-agent llm_config used to be
-- able to override the endpoint, which let anyone with dashboard access point
-- the worker (carrying the provider API key) at an arbitrary address.  The
-- endpoint now comes only from argo_private.llm_providers, which is
-- operator-managed and validated by the outbound guard.
CREATE OR REPLACE FUNCTION argo_private.sanitize_llm_config(p jsonb)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
AS $fn$
  SELECT jsonb_strip_nulls(jsonb_build_object(
    'model',       NULLIF(p->>'model', ''),
    'temperature', p->'temperature',
    'max_tokens',  p->'max_tokens',
    'provider',    NULLIF(p->>'provider', '')
  ))
$fn$;

CREATE OR REPLACE FUNCTION argo_private.extract_first_json(p_text text)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $fn$
DECLARE
  i int;
  start_pos int := 0;
  depth int := 0;
  in_str boolean := false;
  esc boolean := false;
  ch text;
  chunk text;
BEGIN
  IF p_text IS NULL OR btrim(p_text) = '' THEN
    RETURN NULL;
  END IF;
  -- Fast path: the whole string is JSON
  BEGIN
    IF left(btrim(p_text), 1) = '{' THEN
      RETURN btrim(p_text)::jsonb;
    END IF;
  EXCEPTION WHEN others THEN
    NULL;
  END;
  FOR i IN 1..length(p_text) LOOP
    ch := substr(p_text, i, 1);
    IF start_pos = 0 THEN
      IF ch = '{' THEN
        start_pos := i;
        depth := 1;
        in_str := false;
        esc := false;
      END IF;
    ELSE
      IF in_str THEN
        IF esc THEN
          esc := false;
        ELSIF ch = E'\\' THEN
          esc := true;
        ELSIF ch = '"' THEN
          in_str := false;
        END IF;
      ELSE
        IF ch = '"' THEN
          in_str := true;
        ELSIF ch = '{' THEN
          depth := depth + 1;
        ELSIF ch = '}' THEN
          depth := depth - 1;
          IF depth = 0 THEN
            chunk := substr(p_text, start_pos, i - start_pos + 1);
            BEGIN
              RETURN chunk::jsonb;
            EXCEPTION WHEN others THEN
              start_pos := 0;
            END;
          END IF;
        END IF;
      END IF;
    END IF;
  END LOOP;
  RETURN NULL;
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.log_content_text(p jsonb)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $fn$
  SELECT CASE
    WHEN p IS NULL THEN ''
    WHEN jsonb_typeof(p) = 'string' THEN p #>> '{}'
    ELSE p::text
  END
$fn$;

CREATE OR REPLACE FUNCTION argo_private.append_log(
  p_task_id uuid,
  p_step int,
  p_role text,
  p_content jsonb
) RETURNS void
LANGUAGE sql
AS $fn$
  INSERT INTO argo_private.execution_logs (task_id, step_number, role, content)
  VALUES (p_task_id, p_step, p_role, p_content)
$fn$;

CREATE OR REPLACE FUNCTION argo_private.maybe_complete_session(p_session_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_open int;
  v_failed int;
  v_answer text;
BEGIN
  SELECT
    count(*) FILTER (WHERE status IN ('queued', 'running', 'waiting_human')),
    count(*) FILTER (WHERE status = 'failed')
  INTO v_open, v_failed
  FROM argo_private.tasks
  WHERE session_id = p_session_id;

  IF v_open > 0 THEN
    RETURN;
  END IF;

  SELECT t.output->>'answer'
  INTO v_answer
  FROM argo_private.tasks t
  WHERE t.session_id = p_session_id
    AND t.status = 'completed'
    AND t.parent_task_id IS NULL
  ORDER BY t.updated_at DESC
  LIMIT 1;

  IF v_failed > 0 AND v_answer IS NULL THEN
    UPDATE argo_private.sessions
    SET status = 'failed', completed_at = now()
    WHERE session_id = p_session_id AND status = 'open';
  ELSE
    UPDATE argo_private.sessions
    SET status = 'completed',
        final_answer = COALESCE(v_answer, final_answer),
        completed_at = now()
    WHERE session_id = p_session_id AND status = 'open';
  END IF;
END;
$fn$;

-- Authorisation for agent-visible views lives in the views, so it holds even if
-- the statement analysis in fn_execute_sql misses a reference.  An agent that
-- reaches a view it has no permission for sees no rows rather than a leak.
CREATE OR REPLACE FUNCTION argo_private.agent_may_read(p_ref text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
  SELECT argo_private.current_agent_id() IS NOT NULL
     AND EXISTS (
       SELECT 1 FROM argo_private.sql_sandbox_allowlist a
       WHERE a.resource_ref = p_ref
     )
     AND EXISTS (
       SELECT 1 FROM argo_private.permissions p
       WHERE p.agent_id = argo_private.current_agent_id()
         AND p.resource_type = 'view'
         AND p.resource_ref = p_ref
     )
$fn$;

CREATE OR REPLACE VIEW argo_public.v_my_tasks
  WITH (security_barrier = true)
AS
  SELECT
    task_id,
    session_id,
    status,
    step_count,
    created_at,
    updated_at
  FROM argo_private.tasks
  WHERE agent_id IS NOT DISTINCT FROM argo_private.current_agent_id()
    AND argo_private.agent_may_read('argo_public.v_my_tasks');

CREATE OR REPLACE VIEW argo_public.v_sales
  WITH (security_barrier = true)
AS
  SELECT sale_id, region, sku, amount, sold_on
  FROM argo_private.demo_sales
  WHERE agent_id IS NOT DISTINCT FROM argo_private.current_agent_id()
    AND argo_private.agent_may_read('argo_public.v_sales');

-- ---------------------------------------------------------------------------
-- 4. Outbound URL / host guards.
--
-- One implementation, used by every outbound path: the LLM endpoint, the
-- http_get tool, and the OAuth token exchange.  Previously only http_get was
-- guarded, so an operator-set (or dashboard-set) provider base_url could reach
-- link-local metadata services with the provider credentials attached.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_private.url_host(p_url text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $fn$
DECLARE
  v_auth text;
  v_host text;
BEGIN
  IF p_url IS NULL THEN
    RETURN NULL;
  END IF;
  -- Whitespace or control characters mean the URL was built by string
  -- concatenation somewhere; refuse to guess what a client would parse.
  IF p_url ~ '[[:space:][:cntrl:]]' THEN
    RETURN NULL;
  END IF;

  v_auth := (regexp_match(p_url, '^[a-zA-Z][a-zA-Z0-9+.-]*://([^/?#]*)'))[1];
  IF v_auth IS NULL OR v_auth = '' THEN
    RETURN NULL;
  END IF;

  -- userinfo@host is the classic host-confusion trick; different parsers pick
  -- different hosts.  Refuse the whole URL rather than pick one.
  IF position('@' IN v_auth) > 0 THEN
    RETURN NULL;
  END IF;

  IF left(v_auth, 1) = '[' THEN
    v_host := split_part(substring(v_auth from 2), ']', 1);
  ELSE
    v_host := v_auth;
    -- A single colon is host:port.  More than one means a bare IPv6 literal.
    IF length(v_host) - length(replace(v_host, ':', '')) = 1 THEN
      v_host := split_part(v_host, ':', 1);
    END IF;
  END IF;

  v_host := lower(regexp_replace(btrim(v_host), '\.$', ''));
  RETURN nullif(v_host, '');
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.is_blocked_host(p_host text)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
AS $fn$
DECLARE
  h  text := lower(coalesce(p_host, ''));
  v4 text;
BEGIN
  IF h = '' THEN
    RETURN true;
  END IF;

  -- IPv4-mapped / -compatible IPv6 (::ffff:127.0.0.1) reduces to its IPv4 part.
  v4 := (regexp_match(h, '^::(ffff:)?([0-9]{1,3}(\.[0-9]{1,3}){3})$'))[2];
  IF v4 IS NOT NULL THEN
    RETURN argo_private.is_blocked_host(v4);
  END IF;

  -- Non dotted-quad spellings of an IPv4 address (2130706433, 0x7f000001,
  -- 0177.0.0.1) all resolve to the same place but dodge dotted-quad regexes.
  IF h ~ '^[0-9]+$' OR h ~ '^0x[0-9a-f]+$' OR h ~ '^0[0-7]*(\.|$)' THEN
    RETURN true;
  END IF;

  IF h IN ('localhost', 'localhost.localdomain', 'ip6-localhost', 'ip6-loopback') THEN
    RETURN true;
  END IF;
  IF h ~ '(^|\.)(local|localhost|internal|intranet|corp|home|lan)$' THEN
    RETURN true;
  END IF;

  -- IPv6
  IF h IN ('::', '::1') THEN
    RETURN true;
  END IF;
  IF h ~ '^f[cd][0-9a-f]{2}:' THEN          -- fc00::/7  unique local
    RETURN true;
  END IF;
  IF h ~ '^fe[89ab][0-9a-f]:' THEN          -- fe80::/10 link local
    RETURN true;
  END IF;

  -- IPv4 literals
  IF h ~ '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' THEN
    RETURN h ~ '^(0|10|127)\.'
        OR h ~ '^169\.254\.'
        OR h ~ '^172\.(1[6-9]|2[0-9]|3[01])\.'
        OR h ~ '^192\.168\.'
        OR h ~ '^192\.0\.[02]\.'
        OR h ~ '^198\.1[89]\.'
        OR h ~ '^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.'   -- CGNAT 100.64/10
        OR h ~ '^(22[4-9]|2[3-5][0-9])\.'                          -- multicast + reserved
        OR h = '255.255.255.255';
  END IF;

  RETURN false;
END;
$fn$;

-- Returns NULL when the URL may be fetched, otherwise a short machine-readable
-- reason.  p_allow_private is the per-provider opt-in for loopback/RFC1918.
CREATE OR REPLACE FUNCTION argo_private.check_outbound_url(
  p_url text,
  p_allow_private boolean DEFAULT false
) RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $fn$
DECLARE
  v_scheme text;
  v_host   text;
BEGIN
  IF p_url IS NULL OR btrim(p_url) = '' THEN
    RETURN 'missing_url';
  END IF;
  IF p_url ~ '[[:space:][:cntrl:]]' THEN
    RETURN 'url_has_control_characters';
  END IF;

  v_scheme := lower(coalesce((regexp_match(p_url, '^([a-zA-Z][a-zA-Z0-9+.-]*)://'))[1], ''));
  IF v_scheme = '' THEN
    RETURN 'url_missing_scheme';
  END IF;
  IF v_scheme NOT IN ('http', 'https') THEN
    RETURN 'scheme_not_allowed';
  END IF;
  IF v_scheme = 'http' AND NOT coalesce(p_allow_private, false) THEN
    RETURN 'plaintext_http_not_allowed';
  END IF;

  v_host := argo_private.url_host(p_url);
  IF v_host IS NULL THEN
    RETURN 'url_host_unparseable';
  END IF;
  IF argo_private.is_blocked_host(v_host) AND NOT coalesce(p_allow_private, false) THEN
    RETURN 'host_blocked';
  END IF;

  RETURN NULL;
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 5. Provider secret storage.
--
-- Secrets are encrypted at rest with pgcrypto when both pgcrypto is installed
-- and `allgres.secret_key` is set in postgresql.conf.  Without a key they fall
-- back to plaintext, and settings.get reports which mode is in effect so the
-- dashboard can say so out loud instead of implying protection that is not
-- there.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_private.secret_key()
RETURNS text
LANGUAGE sql
STABLE
AS $fn$
  SELECT nullif(current_setting('allgres.secret_key', true), '')
$fn$;

CREATE OR REPLACE FUNCTION argo_private.secret_storage_mode()
RETURNS text
LANGUAGE plpgsql
STABLE
AS $fn$
DECLARE
  v_ok boolean;
BEGIN
  IF argo_private.secret_key() IS NULL THEN
    RETURN 'plaintext_no_key';
  END IF;
  SELECT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'pgp_sym_encrypt') INTO v_ok;
  IF NOT v_ok THEN
    RETURN 'plaintext_no_pgcrypto';
  END IF;
  RETURN 'encrypted';
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.encrypt_secret(p_plain text)
RETURNS text
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_key text := argo_private.secret_key();
  v_out text;
BEGIN
  IF p_plain IS NULL OR p_plain = '' THEN
    RETURN NULL;
  END IF;
  IF v_key IS NULL THEN
    RETURN p_plain;
  END IF;
  -- Dynamic so the extension still installs when pgcrypto is absent.
  BEGIN
    EXECUTE 'SELECT ''enc:v1:'' || armor(pgp_sym_encrypt($1, $2))'
      INTO v_out USING p_plain, v_key;
    RETURN v_out;
  EXCEPTION WHEN others THEN
    RETURN p_plain;
  END;
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.decrypt_secret(p_stored text)
RETURNS text
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_key text := argo_private.secret_key();
  v_out text;
BEGIN
  IF p_stored IS NULL THEN
    RETURN NULL;
  END IF;
  IF left(p_stored, 7) <> 'enc:v1:' THEN
    RETURN p_stored;
  END IF;
  IF v_key IS NULL THEN
    RETURN NULL;
  END IF;
  BEGIN
    EXECUTE 'SELECT pgp_sym_decrypt(dearmor($1), $2)'
      INTO v_out USING substr(p_stored, 8), v_key;
    RETURN v_out;
  EXCEPTION WHEN others THEN
    RETURN NULL;
  END;
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.provider_secret(p_provider_id uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
  SELECT argo_private.decrypt_secret(api_key)
  FROM argo_private.llm_secrets
  WHERE provider_id = p_provider_id
$fn$;

-- ---------------------------------------------------------------------------
-- 6. SQL sandbox.
--
-- What an agent statement is allowed to touch is decided from PostgreSQL's own
-- parse tree (allgres.analyze_sql -> raw_parser), not from pattern matching the
-- statement text.  The previous regex layer had to re-implement lexing, and
-- comment injection, quoted identifiers, comma joins and `extract(x FROM y)`
-- were all ways for it to be wrong in one direction or the other.
--
-- Layering, strongest first:
--   a. the statement runs as `sandbox` with search_path = pg_temp, so an
--      unqualified relation name cannot resolve to anything at all;
--   b. the views themselves return no rows unless the current agent holds the
--      matching permission (argo_private.agent_may_read), so authorisation does
--      not depend on the analysis being complete;
--   c. transaction_read_only + statement_timeout;
--   d. the parse tree must be exactly one non-writing SELECT;
--   e. every relation it names must be schema-qualified, outside the reserved
--      schemas, and in allowlist n per-agent permission.
--
-- (d) and (e) exist so the model gets a precise error.  (a), (b) and (c) are
-- what contain a statement that gets past them.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_private.fn_execute_sql(p_agent_id uuid, p_sql text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  c_reserved constant text[] := ARRAY[
    'argo_private', 'allgres', 'pg_catalog', 'pg_toast', 'information_schema'
  ];

  v_sql      text;
  v_tree     jsonb;
  v_ctes     text[];
  v_rel      jsonb;
  v_schema   text;
  v_ref      text;
  v_ok       boolean;
  v_rows     jsonb;
  v_n        int;
  v_truncated boolean := false;
BEGIN
  PERFORM set_config('statement_timeout', '5000', true);

  v_sql := btrim(coalesce(p_sql, ''));
  -- The statement is wrapped in a subquery below, so a trailing terminator has
  -- to go even though the parser itself tolerates it.
  v_sql := regexp_replace(v_sql, ';+\s*$', '');
  IF v_sql = '' THEN
    RAISE EXCEPTION 'fn_execute_sql: empty sql' USING ERRCODE = 'P0001';
  END IF;
  IF length(v_sql) > 8000 THEN
    RAISE EXCEPTION 'fn_execute_sql: statement too long' USING ERRCODE = 'P0001';
  END IF;

  -- Parse only: no planning, no rewriting, no execution.  A syntax error
  -- surfaces here as an ordinary exception.
  BEGIN
    v_tree := allgres.analyze_sql(v_sql);
  EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'fn_execute_sql: not parseable as SQL: %', SQLERRM
      USING ERRCODE = 'P0001';
  END;

  IF NOT COALESCE((v_tree->>'ok')::boolean, false) THEN
    RAISE EXCEPTION 'fn_execute_sql: statement could not be analysed'
      USING ERRCODE = 'P0001';
  END IF;

  IF (v_tree->>'statements')::int <> 1 THEN
    RAISE EXCEPTION 'fn_execute_sql: expected one statement, found %',
      v_tree->>'statements' USING ERRCODE = 'P0001';
  END IF;

  IF v_tree->>'kind' <> 'select' THEN
    RAISE EXCEPTION 'fn_execute_sql: only SELECT / WITH ... SELECT is allowed'
      USING ERRCODE = 'P0001';
  END IF;

  -- Covers SELECT ... INTO and data-modifying CTEs, both of which parse as a
  -- SelectStmt and both of which write.
  IF COALESCE((v_tree->>'writes')::boolean, false) THEN
    RAISE EXCEPTION 'fn_execute_sql: statement writes; only reads are allowed'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT coalesce(array_agg(value #>> '{}'), '{}')
  INTO v_ctes
  FROM jsonb_array_elements(COALESCE(v_tree->'ctes', '[]'::jsonb));

  FOR v_rel IN SELECT jsonb_array_elements(COALESCE(v_tree->'relations', '[]'::jsonb)) LOOP
    v_schema := v_rel->>'schema';

    IF v_schema IS NULL THEN
      -- The parser cannot tell a CTE reference from a table reference; the CTE
      -- list it returns is what disambiguates them.
      CONTINUE WHEN (v_rel->>'name') = ANY (v_ctes);
      RAISE EXCEPTION 'fn_execute_sql: unqualified name "%" rejected', v_rel->>'name'
        USING ERRCODE = 'P0001';
    END IF;

    IF lower(v_schema) = ANY (c_reserved) OR lower(v_schema) LIKE 'pg\_%' THEN
      RAISE EXCEPTION 'fn_execute_sql: schema "%" is not readable by agents', v_schema
        USING ERRCODE = 'P0001';
    END IF;

    v_ref := v_schema || '.' || (v_rel->>'name');
    SELECT EXISTS (
      SELECT 1 FROM argo_private.sql_sandbox_allowlist a
      WHERE a.resource_ref = v_ref
    ) AND EXISTS (
      SELECT 1 FROM argo_private.permissions p
      WHERE p.agent_id = p_agent_id
        AND p.resource_type = 'view'
        AND p.resource_ref = v_ref
    )
    INTO v_ok;
    IF NOT v_ok THEN
      RAISE EXCEPTION 'fn_execute_sql: "%" not in allowlist', v_ref
        USING ERRCODE = 'P0001';
    END IF;
  END LOOP;

  PERFORM set_config('argo.agent_id', p_agent_id::text, true);

  -- Fail closed: never execute model-generated SQL with the SECURITY DEFINER owner.
  BEGIN
    EXECUTE 'SET LOCAL ROLE sandbox';
  EXCEPTION
    WHEN undefined_object OR invalid_authorization_specification OR insufficient_privilege THEN
      RAISE EXCEPTION 'fn_execute_sql: sandbox role unavailable or cannot be assumed'
        USING ERRCODE = 'P0001';
  END;

  -- With pg_temp only, an unqualified relation name resolves to nothing.
  PERFORM set_config('search_path', 'pg_temp', true);
  PERFORM set_config('transaction_read_only', 'on', true);
  PERFORM set_config('statement_timeout', '5s', true);

  -- Safe to wrap in a subquery: the parser has already confirmed v_sql is one
  -- complete SELECT, so it cannot terminate the enclosing expression.
  BEGIN
    EXECUTE 'SELECT coalesce(jsonb_agg(q.row), ''[]''::jsonb) FROM (SELECT to_jsonb(s) AS row FROM ('
      || v_sql
      || ') s LIMIT 201) q'
      INTO v_rows;
  EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'fn_execute_sql: engine rejected query: %', SQLERRM
      USING ERRCODE = 'P0001';
  END;

  v_n := coalesce(jsonb_array_length(v_rows), 0);
  IF v_n > 200 THEN
    v_rows := (SELECT jsonb_agg(x) FROM jsonb_array_elements(v_rows) WITH ORDINALITY e(x, n) WHERE n <= 200);
    v_truncated := true;
    v_n := 200;
  END IF;
  IF octet_length(v_rows::text) > 65536 THEN
    WHILE octet_length(v_rows::text) > 65536 AND jsonb_array_length(v_rows) > 1 LOOP
      v_rows := v_rows - (jsonb_array_length(v_rows) - 1);
      v_truncated := true;
    END LOOP;
    v_n := jsonb_array_length(v_rows);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'row_count', v_n,
    'truncated', v_truncated,
    'rows', v_rows
  );
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 7. Agent state machine.  Short transactions only; never waits on HTTP.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_public.fn_next_step(p_task_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  t argo_private.tasks%ROWTYPE;
  a argo_private.agents%ROWTYPE;
  p argo_private.policies%ROWTYPE;
  v_messages jsonb := '[]'::jsonb;
  v_log record;
  v_has_input boolean;
  v_views jsonb;
  v_tools jsonb;
  v_input_text text;
  v_cfg jsonb;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);

  SELECT * INTO t
  FROM argo_private.tasks
  WHERE task_id = p_task_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'fn_next_step: task not found' USING ERRCODE = 'P0001';
  END IF;

  IF t.status NOT IN ('queued', 'running') THEN
    RAISE EXCEPTION 'fn_next_step: status % not runnable', t.status
      USING ERRCODE = 'P0001';
  END IF;

  IF t.status = 'queued' THEN
    UPDATE argo_private.tasks
    SET status = 'running', updated_at = now()
    WHERE task_id = p_task_id;
    t.status := 'running';
  END IF;

  SELECT * INTO a FROM argo_private.agents WHERE agent_id = t.agent_id;
  SELECT * INTO p FROM argo_private.policies WHERE agent_id = t.agent_id;

  IF a IS NULL OR NOT a.is_active THEN
    UPDATE argo_private.tasks
    SET status = 'failed', error = 'agent_inactive', updated_at = now()
    WHERE task_id = p_task_id;
    PERFORM argo_private.append_log(
      p_task_id, t.step_count, 'error',
      jsonb_build_object('reason', 'agent_inactive')
    );
    PERFORM argo_private.maybe_complete_session(t.session_id);
    RETURN jsonb_build_object('action', 'done', 'reason', 'agent_inactive');
  END IF;

  IF p IS NULL THEN
    RAISE EXCEPTION 'fn_next_step: policy missing' USING ERRCODE = 'P0001';
  END IF;

  IF t.step_count >= p.max_steps THEN
    UPDATE argo_private.tasks
    SET status = 'failed', error = 'max_steps', updated_at = now()
    WHERE task_id = p_task_id;
    PERFORM argo_private.append_log(
      p_task_id, t.step_count, 'error',
      jsonb_build_object('reason', 'max_steps', 'max_steps', p.max_steps)
    );
    PERFORM argo_private.maybe_complete_session(t.session_id);
    RETURN jsonb_build_object('action', 'done', 'reason', 'max_steps');
  END IF;

  SELECT coalesce(jsonb_agg(resource_ref ORDER BY resource_ref), '[]'::jsonb)
  INTO v_views
  FROM argo_private.permissions
  WHERE agent_id = t.agent_id AND resource_type = 'view';

  SELECT coalesce(jsonb_agg(resource_ref ORDER BY resource_ref), '[]'::jsonb)
  INTO v_tools
  FROM argo_private.permissions
  WHERE agent_id = t.agent_id AND resource_type = 'tool';

  -- Bounds come from the database, not from worker code, so revoking a
  -- permission takes effect on the very next step.
  v_messages := v_messages || jsonb_build_array(
    jsonb_build_object(
      'role', 'system',
      'content',
      p.system_prompt
      || E'\n\n# bounds (authoritative, from the database)\nviews: '
      || v_views::text
      || E'\ntools: '
      || v_tools::text
      || E'\nPick action from final_answer | execute_sql | call_tool | delegate | await_human.'
      || E'\nFor numeric questions, execute_sql first. Do not invent keys.'
    )
  );

  FOR v_log IN
    SELECT role, content
    FROM argo_private.execution_logs
    WHERE task_id = p_task_id
    ORDER BY step_number, created_at
  LOOP
    IF v_log.role IN ('system', 'user', 'assistant', 'tool') THEN
      v_messages := v_messages || jsonb_build_array(
        jsonb_build_object(
          'role', CASE WHEN v_log.role = 'tool' THEN 'user' ELSE v_log.role END,
          'content', argo_private.log_content_text(v_log.content)
        )
      );
    ELSIF v_log.role = 'error' THEN
      v_messages := v_messages || jsonb_build_array(
        jsonb_build_object(
          'role', 'user',
          'content', 'Previous step error: ' || argo_private.log_content_text(v_log.content)
          || '. Reply with a valid action JSON.'
        )
      );
    END IF;
  END LOOP;

  v_input_text := COALESCE(t.input->>'goal', t.input->>'text', t.input::text);
  SELECT EXISTS (
    SELECT 1 FROM argo_private.execution_logs
    WHERE task_id = p_task_id AND role = 'user'
  ) INTO v_has_input;
  IF NOT v_has_input AND v_input_text IS NOT NULL AND v_input_text NOT IN ('', '{}') THEN
    v_messages := v_messages || jsonb_build_array(
      jsonb_build_object('role', 'user', 'content', v_input_text)
    );
  END IF;

  v_cfg := argo_private.sanitize_llm_config(p.llm_config);

  RETURN jsonb_build_object(
    'action', 'call_llm',
    'task_id', t.task_id,
    'agent_id', t.agent_id,
    'session_id', t.session_id,
    'step', t.step_count + 1,
    'messages', v_messages,
    'llm_config', v_cfg,
    'bounds', jsonb_build_object(
      'views', v_views,
      'tools', v_tools,
      'max_steps', p.max_steps
    )
  );
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_submit_result(p_task_id uuid, p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  t argo_private.tasks%ROWTYPE;
  a argo_private.agents%ROWTYPE;
  p argo_private.policies%ROWTYPE;
  v_type text;
  v_parsed jsonb;
  v_action text;
  v_sql_result jsonb;
  v_tool text;
  v_args jsonb;
  v_target uuid;
  v_child uuid;
  v_err_n int;
  v_allowed boolean;
  v_url text;
  v_host text;
  v_reason text;
  v_call uuid;
  v_answer text;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);

  SELECT * INTO t
  FROM argo_private.tasks
  WHERE task_id = p_task_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'fn_submit_result: task not found' USING ERRCODE = 'P0001';
  END IF;
  IF t.status <> 'running' THEN
    RAISE EXCEPTION 'fn_submit_result: status % is not running', t.status
      USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO a FROM argo_private.agents WHERE agent_id = t.agent_id;
  SELECT * INTO p FROM argo_private.policies WHERE agent_id = t.agent_id;

  IF a IS NULL OR NOT a.is_active THEN
    UPDATE argo_private.tasks
    SET status = 'failed', error = 'agent_inactive', updated_at = now()
    WHERE task_id = p_task_id;
    PERFORM argo_private.append_log(
      p_task_id, t.step_count, 'error',
      jsonb_build_object('reason', 'agent_inactive', 'discarded', true)
    );
    PERFORM argo_private.maybe_complete_session(t.session_id);
    RETURN jsonb_build_object('action', 'done', 'reason', 'agent_inactive');
  END IF;

  v_type := p_payload->>'type';
  IF v_type IS NULL OR v_type NOT IN ('llm_response', 'tool_result', 'error') THEN
    PERFORM argo_private.append_log(
      p_task_id, t.step_count, 'error',
      jsonb_build_object('reason', 'payload_rejected', 'payload', p_payload)
    );
    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'continue', 'reason', 'payload_rejected');
  END IF;

  IF v_type = 'error' THEN
    PERFORM argo_private.append_log(
      p_task_id, t.step_count + 1, 'error',
      jsonb_build_object('message', COALESCE(p_payload->>'message', 'error'))
    );
    SELECT count(*) INTO v_err_n
    FROM argo_private.execution_logs
    WHERE task_id = p_task_id AND role = 'error';
    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    IF v_err_n > p.max_retries THEN
      UPDATE argo_private.tasks
      SET status = 'failed', error = COALESCE(p_payload->>'message', 'error'), updated_at = now()
      WHERE task_id = p_task_id;
      PERFORM argo_private.maybe_complete_session(t.session_id);
      RETURN jsonb_build_object('action', 'done', 'reason', 'retries_exceeded');
    END IF;
    RETURN jsonb_build_object('action', 'continue');
  END IF;

  IF v_type = 'tool_result' THEN
    PERFORM argo_private.append_log(
      p_task_id, t.step_count + 1, 'tool',
      COALESCE(p_payload->'content', '{}'::jsonb)
    );
    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'continue');
  END IF;

  -- llm_response
  PERFORM argo_private.append_log(
    p_task_id, t.step_count + 1, 'assistant',
    to_jsonb(COALESCE(p_payload->>'content', ''))
  );

  v_parsed := p_payload->'parsed';
  IF v_parsed IS NULL OR jsonb_typeof(v_parsed) <> 'object' THEN
    v_parsed := argo_private.extract_first_json(p_payload->>'content');
  END IF;

  v_action := v_parsed->>'action';
  IF v_action IS NULL OR v_action NOT IN (
    'final_answer', 'execute_sql', 'call_tool', 'delegate', 'await_human'
  ) THEN
    PERFORM argo_private.append_log(
      p_task_id, t.step_count + 1, 'error',
      jsonb_build_object('reason', 'unknown_action', 'parsed', v_parsed)
    );
    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'continue', 'reason', 'unknown_action');
  END IF;

  IF v_action = 'final_answer' THEN
    v_answer := COALESCE(v_parsed->>'answer', '');
    UPDATE argo_private.tasks
    SET status = 'completed',
        output = jsonb_build_object('answer', v_answer),
        step_count = step_count + 1,
        updated_at = now()
    WHERE task_id = p_task_id;
    UPDATE argo_private.sessions
    SET final_answer = v_answer
    WHERE session_id = t.session_id;
    PERFORM argo_private.maybe_complete_session(t.session_id);
    RETURN jsonb_build_object('action', 'done');
  END IF;

  IF v_action = 'execute_sql' THEN
    BEGIN
      v_sql_result := argo_private.fn_execute_sql(t.agent_id, v_parsed->>'sql');
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'tool',
        jsonb_build_object('sql', v_parsed->>'sql', 'result', v_sql_result)
      );
    EXCEPTION WHEN others THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('sql', v_parsed->>'sql', 'message', SQLERRM)
      );
    END;
    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'continue');
  END IF;

  IF v_action = 'call_tool' THEN
    v_tool := v_parsed->>'tool';
    v_args := COALESCE(v_parsed->'args', '{}'::jsonb);
    SELECT EXISTS (
      SELECT 1 FROM argo_private.permissions
      WHERE agent_id = t.agent_id
        AND resource_type = 'tool'
        AND resource_ref = v_tool
    ) INTO v_allowed;
    IF NOT v_allowed THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', 'tool_not_permitted', 'tool', v_tool)
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;

    IF v_tool <> 'http_get' THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', 'unknown_tool', 'tool', v_tool)
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;

    v_url := v_args->>'url';
    v_reason := argo_private.check_outbound_url(v_url, false);
    IF v_reason IS NOT NULL THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', v_reason, 'url', v_url)
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;

    v_host := argo_private.url_host(v_url);
    SELECT EXISTS (
      SELECT 1 FROM argo_private.permissions
      WHERE agent_id = t.agent_id
        AND resource_type = 'http_host'
        AND lower(resource_ref) = v_host
    ) INTO v_allowed;
    IF NOT v_allowed THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', 'http_host_not_permitted', 'host', v_host)
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;

    INSERT INTO argo_private.outbound_calls (
      task_id, kind, tool, url, request_headers, request_body, status
    ) VALUES (
      p_task_id, 'tool', v_tool, v_url,
      jsonb_build_object('accept', 'application/json, text/plain, */*'),
      '{}'::jsonb, 'queued'
    ) RETURNING call_id INTO v_call;

    UPDATE argo_private.tasks
    SET step_count = step_count + 1, updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'call_tool', 'tool', v_tool, 'args', v_args, 'call_id', v_call);
  END IF;

  IF v_action = 'delegate' THEN
    SELECT agent_id INTO v_target
    FROM argo_private.agents
    WHERE name = v_parsed->>'agent_name' AND is_active;
    IF v_target IS NULL THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', 'delegate_unknown', 'agent_name', v_parsed->>'agent_name')
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;
    SELECT EXISTS (
      SELECT 1 FROM argo_private.permissions
      WHERE agent_id = t.agent_id
        AND resource_type = 'agent'
        AND resource_ref = v_parsed->>'agent_name'
    ) INTO v_allowed;
    IF NOT v_allowed THEN
      PERFORM argo_private.append_log(
        p_task_id, t.step_count + 1, 'error',
        jsonb_build_object('reason', 'delegate_not_permitted', 'agent_name', v_parsed->>'agent_name')
      );
      UPDATE argo_private.tasks
      SET step_count = step_count + 1, updated_at = now()
      WHERE task_id = p_task_id;
      RETURN jsonb_build_object('action', 'continue');
    END IF;
    INSERT INTO argo_private.tasks (
      session_id, agent_id, parent_task_id, status, input
    ) VALUES (
      t.session_id, v_target, p_task_id, 'queued',
      COALESCE(v_parsed->'input', '{}'::jsonb)
    ) RETURNING task_id INTO v_child;
    UPDATE argo_private.tasks
    SET status = 'completed',
        output = jsonb_build_object('child_task_id', v_child),
        step_count = step_count + 1,
        updated_at = now()
    WHERE task_id = p_task_id;
    RETURN jsonb_build_object('action', 'continue', 'child_task_id', v_child);
  END IF;

  IF v_action = 'await_human' THEN
    UPDATE argo_private.tasks
    SET status = 'waiting_human',
        step_count = step_count + 1,
        updated_at = now()
    WHERE task_id = p_task_id;
    INSERT INTO argo_private.human_approvals (task_id, status, payload)
    VALUES (
      p_task_id, 'pending',
      jsonb_build_object('reason', COALESCE(v_parsed->>'reason', ''))
    );
    RETURN jsonb_build_object('action', 'wait');
  END IF;

  RETURN jsonb_build_object('action', 'continue');
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 8. Pump.  Builds requests; HTTP happens after these functions commit.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_private.build_llm_http(
  p_spec jsonb,
  p_fallback_key text
) RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  v_cfg jsonb := COALESCE(p_spec->'llm_config', '{}'::jsonb);
  v_name text := COALESCE(v_cfg->>'provider', 'xai');
  v_prov argo_private.llm_providers%ROWTYPE;
  v_key text;
  v_url text;
  v_reason text;
  v_headers jsonb;
  v_body jsonb;
  v_model text;
  v_msgs jsonb := COALESCE(p_spec->'messages', '[]'::jsonb);
  v_system text := '';
  v_rest jsonb := '[]'::jsonb;
  v_el jsonb;
BEGIN
  SELECT * INTO v_prov
  FROM argo_private.llm_providers
  WHERE name = v_name AND is_enabled
  LIMIT 1;

  IF NOT FOUND THEN
    SELECT * INTO v_prov
    FROM argo_private.llm_providers
    WHERE is_enabled
    ORDER BY name
    LIMIT 1;
  END IF;

  IF v_prov.provider_id IS NULL THEN
    RAISE EXCEPTION 'no enabled llm provider' USING ERRCODE = 'P0001';
  END IF;

  v_key := argo_private.provider_secret(v_prov.provider_id);
  IF (v_key IS NULL OR v_key = '') AND v_prov.name IN ('xai', 'grok') THEN
    v_key := NULLIF(p_fallback_key, '');
  END IF;
  IF v_key IS NULL THEN
    v_key := COALESCE(NULLIF(p_fallback_key, ''), '');
  END IF;

  v_model := COALESCE(v_cfg->>'model', 'grok-4.5');

  -- The endpoint comes only from the provider row.  Per-agent llm_config can no
  -- longer redirect it (see sanitize_llm_config).
  v_url := rtrim(v_prov.base_url, '/');
  v_reason := argo_private.check_outbound_url(v_url, v_prov.allow_private_network);
  IF v_reason IS NOT NULL THEN
    RAISE EXCEPTION 'llm provider "%" endpoint rejected: %', v_prov.name, v_reason
      USING ERRCODE = 'P0001';
  END IF;

  IF v_prov.kind = 'anthropic' THEN
    FOR v_el IN SELECT jsonb_array_elements(v_msgs) LOOP
      IF v_el->>'role' = 'system' THEN
        v_system := v_system || CASE WHEN v_system = '' THEN '' ELSE E'\n' END || (v_el->>'content');
      ELSE
        v_rest := v_rest || jsonb_build_array(
          jsonb_build_object(
            'role', CASE WHEN v_el->>'role' IN ('assistant', 'user') THEN v_el->>'role' ELSE 'user' END,
            'content', v_el->>'content'
          )
        );
      END IF;
    END LOOP;
    v_url := v_url || '/v1/messages';
    v_headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-api-key', COALESCE(v_key, ''),
      'anthropic-version', '2023-06-01'
    );
    v_body := jsonb_build_object(
      'model', v_model,
      'max_tokens', COALESCE((v_cfg->>'max_tokens')::int, 1024),
      'system', v_system,
      'messages', v_rest
    );
  ELSE
    v_url := v_url || '/chat/completions';
    v_headers := jsonb_build_object(
      'content-type', 'application/json',
      'authorization', 'Bearer ' || COALESCE(v_key, '')
    );
    v_body := jsonb_build_object(
      'model', v_model,
      'messages', v_msgs,
      'temperature', COALESCE((v_cfg->>'temperature')::float, 0.2),
      'max_tokens', COALESCE((v_cfg->>'max_tokens')::int, 1024)
    );
    -- Ollama rejects response_format; everything else parses better with it.
    IF v_prov.name <> 'ollama' THEN
      v_body := v_body || jsonb_build_object(
        'response_format', jsonb_build_object('type', 'json_object')
      );
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'provider', v_prov.name,
    'kind', v_prov.kind,
    'url', v_url,
    'headers', v_headers,
    'body', v_body
  );
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_dispatch_tasks(p_fallback_key text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  t record;
  spec jsonb;
  http jsonb;
  v_id uuid;
  v_n int := 0;
  v_out jsonb := '[]'::jsonb;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);

  FOR t IN
    SELECT task_id
    FROM argo_private.tasks
    WHERE status IN ('queued', 'running')
      AND NOT EXISTS (
        SELECT 1 FROM argo_private.outbound_calls o
        WHERE o.task_id = tasks.task_id
          AND o.status IN ('queued', 'in_flight')
      )
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
  LOOP
    BEGIN
      spec := argo_public.fn_next_step(t.task_id);
    EXCEPTION WHEN others THEN
      CONTINUE;
    END;
    IF spec->>'action' <> 'call_llm' THEN
      CONTINUE;
    END IF;
    BEGIN
      http := argo_private.build_llm_http(spec, p_fallback_key);
    EXCEPTION WHEN others THEN
      PERFORM argo_public.fn_submit_result(
        t.task_id,
        jsonb_build_object('type', 'error', 'message', SQLERRM)
      );
      CONTINUE;
    END;
    INSERT INTO argo_private.outbound_calls (
      task_id, kind, url, request_headers, request_body, status
    ) VALUES (
      t.task_id, 'llm', http->>'url', http->'headers', http->'body', 'queued'
    ) RETURNING call_id INTO v_id;
    v_out := v_out || jsonb_build_array(jsonb_build_object('call_id', v_id, 'task_id', t.task_id));
    v_n := v_n + 1;
    EXIT WHEN v_n >= 4;
  END LOOP;

  RETURN jsonb_build_object('dispatched', v_n, 'calls', v_out);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_claim_outbound(p_limit int DEFAULT 4)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  r record;
  v_out jsonb := '[]'::jsonb;
  v_n int := 0;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);
  FOR r IN
    SELECT call_id, task_id, kind, tool, url, request_headers, request_body
    FROM argo_private.outbound_calls
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 4), 16))
  LOOP
    UPDATE argo_private.outbound_calls
    SET status = 'in_flight', updated_at = now()
    WHERE call_id = r.call_id;
    v_out := v_out || jsonb_build_array(jsonb_build_object(
      'call_id', r.call_id,
      'task_id', r.task_id,
      'kind', r.kind,
      'tool', r.tool,
      'url', r.url,
      'headers', r.request_headers,
      'body', r.request_body
    ));
    v_n := v_n + 1;
  END LOOP;
  RETURN jsonb_build_object('count', v_n, 'calls', v_out);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_private.llm_text_from_http(p_body text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $fn$
DECLARE
  j jsonb;
  t text;
BEGIN
  BEGIN
    j := p_body::jsonb;
  EXCEPTION WHEN others THEN
    RETURN p_body;
  END;
  t := j #>> '{choices,0,message,content}';
  IF t IS NOT NULL THEN
    RETURN t;
  END IF;
  t := j #>> '{content,0,text}';
  IF t IS NOT NULL THEN
    RETURN t;
  END IF;
  RETURN p_body;
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_complete_outbound(
  p_call_id uuid,
  p_status int,
  p_body text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  c argo_private.outbound_calls%ROWTYPE;
  v_text text;
  v_parsed jsonb;
  v_payload jsonb;
  v_result jsonb;
  v_running boolean;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);

  SELECT * INTO c
  FROM argo_private.outbound_calls
  WHERE call_id = p_call_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'fn_complete_outbound: not found' USING ERRCODE = 'P0001';
  END IF;

  UPDATE argo_private.outbound_calls
  SET status = 'harvested',
      response_status = p_status,
      response_body = left(COALESCE(p_body, ''), 200000),
      updated_at = now()
  WHERE call_id = p_call_id;

  IF c.kind = 'tool' THEN
    v_payload := jsonb_build_object(
      'type', 'tool_result',
      'content', jsonb_build_object(
        'status', p_status,
        'body', left(COALESCE(p_body, ''), 16000)
      )
    );
  ELSIF p_status IS NULL OR p_status >= 400 OR p_status < 200 THEN
    v_payload := jsonb_build_object(
      'type', 'error',
      'message', 'llm http ' || COALESCE(p_status::text, '0') || ': ' || left(COALESCE(p_body, ''), 2000)
    );
  ELSE
    v_text := argo_private.llm_text_from_http(p_body);
    v_parsed := argo_private.extract_first_json(v_text);
    v_payload := jsonb_build_object(
      'type', 'llm_response',
      'content', v_text,
      'parsed', v_parsed
    );
  END IF;

  -- The task may have been failed by the watchdog or by max_steps while this
  -- call was in flight.  Harvesting must still commit, so never let
  -- fn_submit_result abort the transaction that records the response.
  SELECT EXISTS (
    SELECT 1 FROM argo_private.tasks WHERE task_id = c.task_id AND status = 'running'
  ) INTO v_running;

  IF v_running THEN
    BEGIN
      v_result := argo_public.fn_submit_result(c.task_id, v_payload);
    EXCEPTION WHEN others THEN
      v_result := jsonb_build_object('action', 'error', 'message', SQLERRM);
    END;
  ELSE
    v_result := jsonb_build_object('action', 'skipped', 'reason', 'task_not_running');
  END IF;

  RETURN jsonb_build_object('submit', v_result, 'call_id', p_call_id);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_watchdog(p_timeout_seconds int DEFAULT 90)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  r record;
  n int := 0;
BEGIN
  PERFORM set_config('statement_timeout', '2000', true);
  FOR r IN
    SELECT call_id, task_id
    FROM argo_private.outbound_calls
    WHERE status = 'in_flight'
      AND updated_at < now() - make_interval(secs => GREATEST(15, COALESCE(p_timeout_seconds, 90)))
    FOR UPDATE SKIP LOCKED
  LOOP
    UPDATE argo_private.outbound_calls
    SET status = 'lost', error = 'timeout', updated_at = now()
    WHERE call_id = r.call_id;
    IF EXISTS (SELECT 1 FROM argo_private.tasks WHERE task_id = r.task_id AND status = 'running') THEN
      BEGIN
        PERFORM argo_public.fn_submit_result(
          r.task_id,
          jsonb_build_object('type', 'error', 'message', 'outbound timeout')
        );
      EXCEPTION WHEN others THEN
        NULL;
      END;
    END IF;
    n := n + 1;
  END LOOP;
  RETURN jsonb_build_object('lost', n);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_pump(p_fallback_key text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  d jsonb;
  c jsonb;
  w jsonb;
BEGIN
  -- Does not perform HTTP.  Caller claims queued rows AFTER this commits.
  w := argo_public.fn_watchdog();
  d := argo_public.fn_dispatch_tasks(p_fallback_key);
  c := argo_public.fn_claim_outbound(4);
  RETURN jsonb_build_object('watchdog', w, 'dispatch', d, 'claim', c);
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 9. Operator API.  The console never SELECTs llm_secrets.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_public.fn_create_agent(p_name text, p_prompt text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  v_id uuid;
BEGIN
  IF btrim(COALESCE(p_name, '')) = '' THEN
    RAISE EXCEPTION 'agent name required' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO argo_private.agents (name)
  VALUES (btrim(p_name))
  RETURNING agent_id INTO v_id;
  IF p_prompt IS NOT NULL AND btrim(p_prompt) <> '' THEN
    UPDATE argo_private.policies
    SET system_prompt = p_prompt, updated_at = now()
    WHERE agent_id = v_id;
  END IF;
  RETURN jsonb_build_object('ok', true, 'agent_id', v_id);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_set_agent_active(p_agent_id uuid, p_active boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
BEGIN
  UPDATE argo_private.agents
  SET is_active = p_active, updated_at = now()
  WHERE agent_id = p_agent_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'agent not found' USING ERRCODE = 'P0001';
  END IF;
  RETURN jsonb_build_object('ok', true, 'is_active', p_active);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_set_policy(
  p_agent_id uuid,
  p_prompt text DEFAULT NULL,
  p_max_steps int DEFAULT NULL,
  p_max_retries int DEFAULT NULL,
  p_llm_config jsonb DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
BEGIN
  UPDATE argo_private.policies
  SET
    system_prompt = COALESCE(NULLIF(p_prompt, ''), system_prompt),
    max_steps = COALESCE(p_max_steps, max_steps),
    max_retries = COALESCE(p_max_retries, max_retries),
    llm_config = CASE
      WHEN p_llm_config IS NULL THEN llm_config
      ELSE argo_private.sanitize_llm_config(llm_config || p_llm_config)
    END,
    updated_at = now()
  WHERE agent_id = p_agent_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'policy not found' USING ERRCODE = 'P0001';
  END IF;
  RETURN jsonb_build_object('ok', true);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_grant_permission(
  p_agent_id uuid, p_type text, p_ref text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
BEGIN
  INSERT INTO argo_private.permissions (agent_id, resource_type, resource_ref)
  VALUES (p_agent_id, p_type, p_ref)
  ON CONFLICT (agent_id, resource_type, resource_ref) DO NOTHING;
  RETURN jsonb_build_object('ok', true);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_revoke_permission(
  p_agent_id uuid, p_type text, p_ref text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
BEGIN
  DELETE FROM argo_private.permissions
  WHERE agent_id = p_agent_id AND resource_type = p_type AND resource_ref = p_ref;
  RETURN jsonb_build_object('ok', true);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_create_session(p_agent_id uuid, p_goal text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v_sid uuid;
  v_tid uuid;
BEGIN
  IF btrim(COALESCE(p_goal, '')) = '' THEN
    RAISE EXCEPTION 'goal required' USING ERRCODE = 'P0001';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM argo_private.agents WHERE agent_id = p_agent_id AND is_active) THEN
    RAISE EXCEPTION 'agent inactive or missing' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO argo_private.sessions (agent_id, goal, status)
  VALUES (p_agent_id, btrim(p_goal), 'open')
  RETURNING session_id INTO v_sid;
  INSERT INTO argo_private.tasks (session_id, agent_id, status, input)
  VALUES (v_sid, p_agent_id, 'queued', jsonb_build_object('goal', btrim(p_goal)))
  RETURNING task_id INTO v_tid;
  INSERT INTO argo_private.execution_logs (task_id, step_number, role, content)
  VALUES (v_tid, 0, 'user', to_jsonb(btrim(p_goal)));
  RETURN jsonb_build_object('ok', true, 'session_id', v_sid, 'task_id', v_tid);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_set_provider_secret(p_provider_id uuid, p_api_key text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
BEGIN
  INSERT INTO argo_private.llm_secrets (provider_id, api_key)
  VALUES (p_provider_id, argo_private.encrypt_secret(NULLIF(p_api_key, '')))
  ON CONFLICT (provider_id) DO UPDATE
    SET api_key = COALESCE(
          argo_private.encrypt_secret(NULLIF(p_api_key, '')),
          argo_private.llm_secrets.api_key
        );
  RETURN jsonb_build_object(
    'ok', true,
    'has_secret', true,
    'storage', argo_private.secret_storage_mode()
  );
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_set_provider(
  p_provider_id uuid,
  p_base_url text DEFAULT NULL,
  p_enabled boolean DEFAULT NULL,
  p_allow_private_network boolean DEFAULT NULL,
  p_oauth_auth_url text DEFAULT NULL,
  p_oauth_token_url text DEFAULT NULL,
  p_oauth_client_id text DEFAULT NULL,
  p_oauth_client_secret text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v_allow  boolean;
  v_url    text;
  v_reason text;
BEGIN
  SELECT COALESCE(p_allow_private_network, allow_private_network),
         rtrim(COALESCE(NULLIF(p_base_url, ''), base_url), '/')
  INTO v_allow, v_url
  FROM argo_private.llm_providers
  WHERE provider_id = p_provider_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'provider not found' USING ERRCODE = 'P0001';
  END IF;

  -- Validate here as well as at request build time, so a bad endpoint is
  -- rejected while the operator is looking at the error.
  v_reason := argo_private.check_outbound_url(v_url, v_allow);
  IF v_reason IS NOT NULL THEN
    RAISE EXCEPTION 'provider endpoint rejected: % (%)', v_reason, v_url
      USING ERRCODE = 'P0001';
  END IF;

  IF p_oauth_auth_url IS NOT NULL AND p_oauth_auth_url <> '' THEN
    v_reason := argo_private.check_outbound_url(p_oauth_auth_url, v_allow);
    IF v_reason IS NOT NULL THEN
      RAISE EXCEPTION 'oauth auth url rejected: %', v_reason USING ERRCODE = 'P0001';
    END IF;
  END IF;
  IF p_oauth_token_url IS NOT NULL AND p_oauth_token_url <> '' THEN
    v_reason := argo_private.check_outbound_url(p_oauth_token_url, v_allow);
    IF v_reason IS NOT NULL THEN
      RAISE EXCEPTION 'oauth token url rejected: %', v_reason USING ERRCODE = 'P0001';
    END IF;
  END IF;

  UPDATE argo_private.llm_providers
  SET
    base_url = v_url,
    is_enabled = COALESCE(p_enabled, is_enabled),
    allow_private_network = v_allow,
    oauth_auth_url = COALESCE(p_oauth_auth_url, oauth_auth_url),
    oauth_token_url = COALESCE(p_oauth_token_url, oauth_token_url),
    oauth_client_id = COALESCE(p_oauth_client_id, oauth_client_id)
  WHERE provider_id = p_provider_id;

  IF p_oauth_client_secret IS NOT NULL AND p_oauth_client_secret <> '' THEN
    INSERT INTO argo_private.llm_secrets (provider_id, oauth_client_secret)
    VALUES (p_provider_id, argo_private.encrypt_secret(p_oauth_client_secret))
    ON CONFLICT (provider_id) DO UPDATE
      SET oauth_client_secret = EXCLUDED.oauth_client_secret;
  END IF;

  RETURN jsonb_build_object('ok', true);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_oauth_start(p_provider_id uuid, p_redirect text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v argo_private.llm_providers%ROWTYPE;
  v_state text := replace(gen_random_uuid()::text, '-', '');
  v_url text;
BEGIN
  SELECT * INTO v FROM argo_private.llm_providers WHERE provider_id = p_provider_id;
  IF v.provider_id IS NULL OR v.kind <> 'oauth' THEN
    RAISE EXCEPTION 'provider is not oauth' USING ERRCODE = 'P0001';
  END IF;
  IF v.oauth_auth_url IS NULL OR v.oauth_client_id IS NULL THEN
    RAISE EXCEPTION 'oauth urls / client id missing' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO argo_private.oauth_states (state, provider_id) VALUES (v_state, p_provider_id);
  v_url := v.oauth_auth_url
    || CASE WHEN v.oauth_auth_url LIKE '%?' THEN '&' ELSE '?' END
    || 'response_type=code'
    || '&client_id=' || replace(v.oauth_client_id, ' ', '%20')
    || '&state=' || v_state
    || '&redirect_uri=' || replace(p_redirect, ' ', '%20')
    || CASE WHEN v.oauth_scope IS NOT NULL THEN '&scope=' || replace(v.oauth_scope, ' ', '%20') ELSE '' END;
  RETURN jsonb_build_object('ok', true, 'redirect_url', v_url, 'state', v_state);
END;
$fn$;

-- OAuth token exchange is queued like an LLM call: SQL builds the request, HTTP
-- runs after commit, SQL stores the tokens.
CREATE OR REPLACE FUNCTION argo_public.fn_oauth_token_request(
  p_state text,
  p_code text,
  p_redirect text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v_pid uuid;
  v argo_private.llm_providers%ROWTYPE;
  v_secret text;
  v_reason text;
BEGIN
  SELECT provider_id INTO v_pid FROM argo_private.oauth_states WHERE state = p_state;
  IF v_pid IS NULL THEN
    RAISE EXCEPTION 'unknown oauth state' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO v FROM argo_private.llm_providers WHERE provider_id = v_pid;
  IF v.oauth_token_url IS NULL OR v.oauth_client_id IS NULL THEN
    RAISE EXCEPTION 'oauth token url / client id missing' USING ERRCODE = 'P0001';
  END IF;

  v_reason := argo_private.check_outbound_url(v.oauth_token_url, v.allow_private_network);
  IF v_reason IS NOT NULL THEN
    RAISE EXCEPTION 'oauth token url rejected: %', v_reason USING ERRCODE = 'P0001';
  END IF;

  SELECT argo_private.decrypt_secret(oauth_client_secret) INTO v_secret
  FROM argo_private.llm_secrets WHERE provider_id = v_pid;

  RETURN jsonb_build_object(
    'ok', true,
    'url', v.oauth_token_url,
    'headers', jsonb_build_object('content-type', 'application/x-www-form-urlencoded'),
    'body', jsonb_build_object(
      'grant_type', 'authorization_code',
      'code', p_code,
      'redirect_uri', p_redirect,
      'client_id', v.oauth_client_id,
      'client_secret', COALESCE(v_secret, '')
    ),
    'state', p_state
  );
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_oauth_store_tokens(
  p_state text,
  p_access text,
  p_refresh text,
  p_expires_in int
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v_pid uuid;
BEGIN
  SELECT provider_id INTO v_pid FROM argo_private.oauth_states WHERE state = p_state;
  IF v_pid IS NULL THEN
    RAISE EXCEPTION 'unknown oauth state' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO argo_private.llm_secrets (provider_id, access_token, refresh_token, expires_at)
  VALUES (
    v_pid,
    argo_private.encrypt_secret(p_access),
    argo_private.encrypt_secret(p_refresh),
    CASE WHEN p_expires_in IS NULL THEN NULL ELSE now() + make_interval(secs => p_expires_in) END
  )
  ON CONFLICT (provider_id) DO UPDATE SET
    access_token = EXCLUDED.access_token,
    refresh_token = COALESCE(EXCLUDED.refresh_token, argo_private.llm_secrets.refresh_token),
    expires_at = EXCLUDED.expires_at;
  DELETE FROM argo_private.oauth_states WHERE state = p_state;
  RETURN jsonb_build_object('ok', true, 'provider_id', v_pid);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_decide_approval(p_approval_id uuid, p_accept boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
DECLARE
  v argo_private.human_approvals%ROWTYPE;
BEGIN
  SELECT * INTO v FROM argo_private.human_approvals WHERE approval_id = p_approval_id FOR UPDATE;
  IF NOT FOUND OR v.status <> 'pending' THEN
    RAISE EXCEPTION 'approval not pending' USING ERRCODE = 'P0001';
  END IF;
  UPDATE argo_private.human_approvals
  SET status = CASE WHEN p_accept THEN 'approved' ELSE 'rejected' END,
      decided_at = now()
  WHERE approval_id = p_approval_id;
  IF p_accept THEN
    UPDATE argo_private.tasks
    SET status = 'queued', updated_at = now()
    WHERE task_id = v.task_id AND status = 'waiting_human';
  ELSE
    UPDATE argo_private.tasks
    SET status = 'failed', error = 'human_rejected', updated_at = now()
    WHERE task_id = v.task_id AND status = 'waiting_human';
    PERFORM argo_private.maybe_complete_session(
      (SELECT session_id FROM argo_private.tasks WHERE task_id = v.task_id)
    );
  END IF;
  RETURN jsonb_build_object('ok', true);
END;
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_allowlist_add(p_ref text)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
  INSERT INTO argo_private.sql_sandbox_allowlist (resource_ref)
  VALUES (p_ref)
  ON CONFLICT DO NOTHING
  RETURNING jsonb_build_object('ok', true, 'resource_ref', resource_ref);
$fn$;

CREATE OR REPLACE FUNCTION argo_public.fn_allowlist_del(p_ref text)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = argo_private, pg_temp
AS $fn$
  DELETE FROM argo_private.sql_sandbox_allowlist WHERE resource_ref = p_ref
  RETURNING jsonb_build_object('ok', true);
$fn$;

CREATE OR REPLACE FUNCTION argo_private.selftest_cleanup()
RETURNS void
LANGUAGE plpgsql
AS $fn$
BEGIN
  UPDATE argo_private.tasks t
  SET status = 'failed', error = 'selftest', updated_at = now()
  FROM argo_private.sessions s
  WHERE t.session_id = s.session_id
    AND s.goal LIKE 'selftest%'
    AND t.status IN ('queued', 'running', 'waiting_human');
  UPDATE argo_private.sessions
  SET status = 'cancelled', completed_at = now()
  WHERE goal LIKE 'selftest%' AND status = 'open';
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 10. Seed data.  Create-only: replaying this file must not clobber an
--     operator's edited prompt, provider list, or policy.
-- ---------------------------------------------------------------------------

INSERT INTO argo_private.llm_providers (name, kind, base_url, is_enabled, allow_private_network)
VALUES
  ('xai',           'openai_compat', 'https://api.x.ai/v1',        true,  false),
  ('openai',        'openai_compat', 'https://api.openai.com/v1',  true,  false),
  ('anthropic',     'anthropic',     'https://api.anthropic.com',  true,  false),
  ('ollama',        'openai_compat', 'http://127.0.0.1:11434/v1',  true,  true),
  ('openai_compat', 'openai_compat', 'https://api.openai.com/v1',  true,  false)
ON CONFLICT (name) DO NOTHING;

INSERT INTO argo_private.sql_sandbox_allowlist (resource_ref)
VALUES ('argo_public.v_sales'), ('argo_public.v_my_tasks')
ON CONFLICT DO NOTHING;

DO $seed$
DECLARE
  v_agent uuid;
BEGIN
  SELECT agent_id INTO v_agent FROM argo_private.agents WHERE name = 'analyst';

  IF v_agent IS NULL THEN
    INSERT INTO argo_private.agents (name) VALUES ('analyst') RETURNING agent_id INTO v_agent;

    -- Only on first creation, so an upgrade never overwrites a tuned policy.
    UPDATE argo_private.policies
    SET system_prompt = $prompt$You are ARGO analyst. Reply with one JSON object only. No markdown, no prose.

Allowed:
{"action":"final_answer","answer":"..."}
{"action":"execute_sql","sql":"SELECT ..."}
{"action":"call_tool","tool":"http_get","args":{"url":"https://..."}}
{"action":"await_human","reason":"..."}

For numbers use execute_sql against argo_public.v_sales (region, sku, amount, sold_on).
Example: {"action":"execute_sql","sql":"SELECT region, sum(amount) AS total FROM argo_public.v_sales GROUP BY region"}
When you have the result, emit final_answer in one short sentence.
$prompt$,
        max_steps = 8,
        max_retries = 2,
        llm_config = jsonb_build_object(
          'provider', 'xai',
          'model', 'grok-4.5',
          'temperature', 0.2,
          'max_tokens', 1024
        ),
        updated_at = now()
    WHERE agent_id = v_agent;
  END IF;

  INSERT INTO argo_private.permissions (agent_id, resource_type, resource_ref)
  SELECT v_agent, x.resource_type, x.resource_ref
  FROM (VALUES
    ('view', 'argo_public.v_sales'),
    ('view', 'argo_public.v_my_tasks'),
    ('tool', 'http_get')
  ) AS x(resource_type, resource_ref)
  ON CONFLICT (agent_id, resource_type, resource_ref) DO NOTHING;

  IF NOT EXISTS (SELECT 1 FROM argo_private.demo_sales WHERE agent_id = v_agent) THEN
    INSERT INTO argo_private.demo_sales (agent_id, region, sku, amount, sold_on)
    SELECT v_agent, s.region, s.sku, s.amount, s.sold_on
    FROM (VALUES
      ('seoul',   'ARB-1', 1200.00, DATE '2026-08-01'),
      ('seoul',   'ARB-2',  840.50, DATE '2026-08-03'),
      ('busan',   'ARB-1',  410.00, DATE '2026-08-04'),
      ('incheon', 'ARB-3', 1920.00, DATE '2026-08-07'),
      ('busan',   'ARB-2',  275.25, DATE '2026-08-12')
    ) AS s(region, sku, amount, sold_on);
  END IF;
END
$seed$;

-- ---------------------------------------------------------------------------
-- 11. Selftest.  Spec section 10 invariants, runnable from the console.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION argo_public.fn_selftest()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, pg_temp
AS $fn$
DECLARE
  v jsonb := '[]'::jsonb;
  v_agent uuid;
  v_sid uuid;
  v_tid uuid;
  v_saved_prompt text;
  spec jsonb;
  sub jsonb;
  r jsonb;
  n_logs int;
  ok boolean;
  detail text;
BEGIN
  SELECT agent_id INTO v_agent FROM argo_private.agents WHERE name = 'analyst' LIMIT 1;
  SELECT system_prompt INTO v_saved_prompt FROM argo_private.policies WHERE agent_id = v_agent;

  -- 1. next_step messages[0] is the current prompt
  UPDATE argo_private.policies
  SET system_prompt = 'PROMPT_A_' || extract(epoch from now())::text
  WHERE agent_id = v_agent;
  v_sid := (argo_public.fn_create_session(v_agent, 'selftest policy')->>'session_id')::uuid;
  SELECT task_id INTO v_tid FROM argo_private.tasks WHERE session_id = v_sid LIMIT 1;
  spec := argo_public.fn_next_step(v_tid);
  ok := (spec->'messages'->0->>'content') LIKE 'PROMPT_A_%';
  v := v || jsonb_build_array(jsonb_build_object('name', 'policy_propagates_to_next_step', 'ok', ok));

  -- 2. inactive agent -> done/failed, no side effect
  UPDATE argo_private.agents SET is_active = false WHERE agent_id = v_agent;
  spec := argo_public.fn_next_step(v_tid);
  ok := spec->>'action' = 'done' AND spec->>'reason' = 'agent_inactive';
  SELECT status INTO detail FROM argo_private.tasks WHERE task_id = v_tid;
  ok := ok AND detail = 'failed';
  v := v || jsonb_build_array(jsonb_build_object('name', 'inactive_agent_fails_task', 'ok', ok));
  UPDATE argo_private.agents SET is_active = true WHERE agent_id = v_agent;

  -- 3. unknown action -> continue, still running
  v_sid := (argo_public.fn_create_session(v_agent, 'selftest unknown')->>'session_id')::uuid;
  SELECT task_id INTO v_tid FROM argo_private.tasks WHERE session_id = v_sid LIMIT 1;
  PERFORM argo_public.fn_next_step(v_tid);
  sub := argo_public.fn_submit_result(v_tid, jsonb_build_object(
    'type', 'llm_response',
    'content', '{"action":"hack_the_planet"}',
    'parsed', jsonb_build_object('action', 'hack_the_planet')
  ));
  SELECT status INTO detail FROM argo_private.tasks WHERE task_id = v_tid;
  ok := sub->>'action' = 'continue' AND detail = 'running';
  v := v || jsonb_build_array(jsonb_build_object('name', 'unknown_action_continue', 'ok', ok));

  -- 4. execute_sql INSERT rejected
  PERFORM argo_public.fn_next_step(v_tid);
  sub := argo_public.fn_submit_result(v_tid, jsonb_build_object(
    'type', 'llm_response',
    'content', '{"action":"execute_sql"}',
    'parsed', jsonb_build_object('action', 'execute_sql', 'sql', 'INSERT INTO argo_private.sessions DEFAULT VALUES')
  ));
  SELECT count(*) INTO n_logs
  FROM argo_private.execution_logs
  WHERE task_id = v_tid AND role = 'error';
  SELECT status INTO detail FROM argo_private.tasks WHERE task_id = v_tid;
  ok := n_logs >= 1 AND detail = 'running';
  v := v || jsonb_build_array(jsonb_build_object('name', 'insert_rejected_stays_running', 'ok', ok));

  -- 5. sandbox rejects everything outside the allowlist
  FOREACH detail IN ARRAY ARRAY[
    'SELECT * FROM argo_private.sessions',
    'select * from ARGO_PRIVATE.SESSIONS',
    'SELECT * FROM argo_private.sessions; SELECT 1',
    E'SELECT * FROM argo_private./*x*/sessions',
    E'SELECT * FROM argo_private.\nsessions',
    'SELECT * FROM sessions',
    'SELECT * FROM "argo_private"."sessions"',
    'WITH x AS (SELECT 1) SELECT * FROM argo_private.sessions',
    -- comma joins used to slip past the parser entirely
    'SELECT * FROM argo_public.v_sales a, argo_private.sessions b',
    'SELECT * FROM argo_public.v_sales, argo_private.demo_sales',
    -- catalogue access in a subquery, not in the top-level FROM
    'SELECT (SELECT count(*) FROM pg_catalog.pg_authid) FROM argo_public.v_sales',
    'SELECT * FROM argo_public.v_sales UNION ALL SELECT * FROM argo_private.demo_sales',
    -- a comment splicing a second relation into the FROM list: the grammar sees
    -- through this, a text scanner has to be taught to
    E'SELECT * FROM argo_public.v_sales --x\n, argo_private.sessions',
    -- SELECT ... INTO and data-modifying CTEs both parse as a SelectStmt
    'SELECT * INTO argo_private.stolen FROM argo_public.v_sales',
    'WITH w AS (DELETE FROM argo_private.sessions RETURNING 1) SELECT * FROM w',
    -- privilege-gated function: rejected by the sandbox role, not by a name list
    'SELECT * FROM pg_ls_dir(''.'')'
  ] LOOP
    BEGIN
      r := argo_private.fn_execute_sql(v_agent, detail);
      ok := false;
    EXCEPTION WHEN others THEN
      ok := true;
    END;
    v := v || jsonb_build_array(jsonb_build_object(
      'name', 'sandbox_reject:' || left(detail, 48),
      'ok', ok
    ));
  END LOOP;

  -- 6. allowed shapes still work (the parser must not be uselessly strict)
  FOREACH detail IN ARRAY ARRAY[
    'SELECT region, amount FROM argo_public.v_sales',
    'SELECT region, sum(amount) AS total FROM argo_public.v_sales GROUP BY region ORDER BY total DESC',
    'WITH x AS (SELECT region, amount FROM argo_public.v_sales) SELECT region FROM x',
    'SELECT n FROM generate_series(1, 3) AS g(n)',
    'SELECT s.region, t.status FROM argo_public.v_sales s, argo_public.v_my_tasks t',
    -- `FROM` as an operator inside extract(); a text scanner reads this as a
    -- relation reference unless it is special-cased
    'SELECT extract(year FROM sold_on) AS y FROM argo_public.v_sales',
    -- a schema name inside a string literal is data, not a reference
    'SELECT ''argo_private.sessions'' AS note FROM argo_public.v_sales',
    'SELECT region FROM argo_public.v_sales WHERE sku = ''ARB-1'' /* join argo_private.x */'
  ] LOOP
    BEGIN
      r := argo_private.fn_execute_sql(v_agent, detail);
      ok := COALESCE((r->>'ok')::boolean, false);
    EXCEPTION WHEN others THEN
      ok := false;
    END;
    v := v || jsonb_build_array(jsonb_build_object(
      'name', 'sandbox_allow:' || left(detail, 48),
      'ok', ok
    ));
  END LOOP;

  -- 7. logs append-only
  BEGIN
    UPDATE argo_private.execution_logs SET role = 'user' WHERE task_id = v_tid;
    ok := false;
  EXCEPTION WHEN others THEN
    ok := true;
  END;
  v := v || jsonb_build_array(jsonb_build_object('name', 'logs_append_only', 'ok', ok));

  -- 8. final_answer completes
  v_sid := (argo_public.fn_create_session(v_agent, 'selftest done')->>'session_id')::uuid;
  SELECT task_id INTO v_tid FROM argo_private.tasks WHERE session_id = v_sid LIMIT 1;
  PERFORM argo_public.fn_next_step(v_tid);
  sub := argo_public.fn_submit_result(v_tid, jsonb_build_object(
    'type', 'llm_response',
    'content', '{"action":"final_answer","answer":"ok"}',
    'parsed', jsonb_build_object('action', 'final_answer', 'answer', 'ok')
  ));
  SELECT status INTO detail FROM argo_private.tasks WHERE task_id = v_tid;
  ok := sub->>'action' = 'done' AND detail = 'completed';
  v := v || jsonb_build_array(jsonb_build_object('name', 'final_answer_completes', 'ok', ok));

  -- 9. outbound guard blocks the SSRF shapes on every path, not just http_get
  ok := argo_private.is_blocked_host('169.254.169.254')
    AND argo_private.is_blocked_host('127.0.0.1')
    AND argo_private.is_blocked_host('::1')
    AND argo_private.is_blocked_host('::ffff:127.0.0.1')
    AND argo_private.is_blocked_host('fd00::1')
    AND argo_private.is_blocked_host('fe80::1')
    AND argo_private.is_blocked_host('2130706433')
    AND argo_private.is_blocked_host('0x7f000001')
    AND argo_private.is_blocked_host('metadata.internal')
    AND argo_private.is_blocked_host('10.1.2.3')
    AND argo_private.is_blocked_host('172.16.0.1')
    AND argo_private.is_blocked_host('100.64.0.1')
    AND NOT argo_private.is_blocked_host('api.openai.com')
    AND NOT argo_private.is_blocked_host('api.x.ai');
  v := v || jsonb_build_array(jsonb_build_object('name', 'blocked_host_matrix', 'ok', ok));

  ok := argo_private.check_outbound_url('https://169.254.169.254/latest/meta-data/') IS NOT NULL
    AND argo_private.check_outbound_url('http://api.openai.com/v1') IS NOT NULL
    AND argo_private.check_outbound_url('file:///etc/passwd') IS NOT NULL
    AND argo_private.check_outbound_url('https://evil.example.com@127.0.0.1/') IS NOT NULL
    AND argo_private.check_outbound_url('https://api.openai.com/v1') IS NULL
    AND argo_private.check_outbound_url('http://127.0.0.1:11434/v1', true) IS NULL;
  v := v || jsonb_build_array(jsonb_build_object('name', 'outbound_url_guard', 'ok', ok));

  -- 10. per-agent llm_config can no longer redirect the provider endpoint
  ok := NOT (argo_private.sanitize_llm_config(
          '{"model":"m","base_url":"http://169.254.169.254"}'::jsonb) ? 'base_url');
  v := v || jsonb_build_array(jsonb_build_object('name', 'llm_config_cannot_set_base_url', 'ok', ok));

  -- 11. the views enforce permission on their own, so authorisation does not
  --     depend on fn_execute_sql having spotted every reference
  PERFORM set_config('argo.agent_id', gen_random_uuid()::text, true);
  SELECT count(*) INTO n_logs FROM argo_public.v_sales;
  ok := (n_logs = 0);
  PERFORM set_config('argo.agent_id', v_agent::text, true);
  SELECT count(*) INTO n_logs FROM argo_public.v_sales;
  ok := ok AND (n_logs > 0);
  PERFORM set_config('argo.agent_id', '', true);
  SELECT count(*) INTO n_logs FROM argo_public.v_sales;
  ok := ok AND (n_logs = 0);
  v := v || jsonb_build_array(jsonb_build_object('name', 'views_enforce_permission', 'ok', ok));

  -- 12. the analyser reads the real parse tree, not the statement text
  ok := (allgres.analyze_sql('SELECT 1')->>'kind') = 'select'
    AND (allgres.analyze_sql('SELECT 1; SELECT 2')->>'statements')::int = 2
    AND (allgres.analyze_sql('UPDATE argo_private.agents SET name = ''x''')->>'kind') = 'other'
    AND (allgres.analyze_sql('SELECT * INTO t FROM argo_public.v_sales')->>'writes')::boolean
    AND (allgres.analyze_sql(
           E'SELECT * FROM argo_public.v_sales --x\n, argo_private.sessions'
         )->'relations') @> '[{"schema":"argo_private","name":"sessions"}]'::jsonb
    AND NOT ((allgres.analyze_sql('SELECT ''argo_private.sessions'' FROM argo_public.v_sales')->'relations')
             @> '[{"schema":"argo_private"}]'::jsonb);
  v := v || jsonb_build_array(jsonb_build_object('name', 'native_parser_analysis', 'ok', ok));

  PERFORM argo_private.selftest_cleanup();

  -- Leave the agent as we found it.
  UPDATE argo_private.policies SET system_prompt = v_saved_prompt WHERE agent_id = v_agent;

  RETURN jsonb_build_object(
    'passed', (SELECT count(*) FROM jsonb_array_elements(v) e WHERE (e->>'ok')::boolean),
    'failed', (SELECT count(*) FROM jsonb_array_elements(v) e WHERE NOT (e->>'ok')::boolean),
    'cases', v
  );
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 12. Grants.
-- ---------------------------------------------------------------------------

REVOKE ALL ON SCHEMA argo_private FROM PUBLIC;
REVOKE ALL ON SCHEMA argo_public FROM PUBLIC;

GRANT USAGE ON SCHEMA argo_public TO worker, operator, sandbox;
GRANT USAGE ON SCHEMA argo_private TO operator;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA argo_private TO operator;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA argo_private TO operator;
ALTER DEFAULT PRIVILEGES IN SCHEMA argo_private
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO operator;

-- Logs are append-only even for operator (the trigger enforces it too).
REVOKE UPDATE, DELETE ON argo_private.execution_logs FROM operator;

REVOKE ALL ON argo_private.llm_secrets FROM PUBLIC;
REVOKE ALL ON argo_private.llm_secrets FROM operator;
REVOKE ALL ON argo_private.llm_secrets FROM worker;

-- The sandbox reaches allowlisted views only; argo_public holds nothing else.
GRANT SELECT ON ALL TABLES IN SCHEMA argo_public TO sandbox;
ALTER DEFAULT PRIVILEGES IN SCHEMA argo_public GRANT SELECT ON TABLES TO sandbox;

REVOKE ALL ON FUNCTION argo_public.fn_next_step(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_submit_result(uuid, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_pump(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_dispatch_tasks(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_claim_outbound(int) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_complete_outbound(uuid, int, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_watchdog(int) FROM PUBLIC;
REVOKE ALL ON FUNCTION argo_public.fn_selftest() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION argo_public.fn_next_step(uuid) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_submit_result(uuid, jsonb) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_pump(text) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_dispatch_tasks(text) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_claim_outbound(int) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_complete_outbound(uuid, int, text) TO worker;
GRANT EXECUTE ON FUNCTION argo_public.fn_watchdog(int) TO worker;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA argo_public TO operator;
REVOKE EXECUTE ON FUNCTION argo_private.fn_execute_sql(uuid, text) FROM worker;
REVOKE EXECUTE ON FUNCTION argo_private.provider_secret(uuid) FROM operator;
REVOKE EXECUTE ON FUNCTION argo_private.provider_secret(uuid) FROM worker;
REVOKE EXECUTE ON FUNCTION argo_private.decrypt_secret(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION argo_private.encrypt_secret(text) FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 13. allgres facade + dashboard RPC.
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS allgres;
COMMENT ON SCHEMA allgres IS 'Allgres public facade. Postgres Is All You Need.';

CREATE OR REPLACE FUNCTION allgres.create_agent(p_name text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path = argo_public, argo_private, pg_temp
AS $$ SELECT argo_public.fn_create_agent(p_name) $$;

-- Returns jsonb: fn_create_session returns an object, and the old `RETURNS uuid`
-- declaration made this function fail its return-type check at CREATE time.
CREATE OR REPLACE FUNCTION allgres.create_session(p_agent_id uuid, p_goal text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path = argo_public, argo_private, pg_temp
AS $$ SELECT argo_public.fn_create_session(p_agent_id, p_goal) $$;

CREATE OR REPLACE FUNCTION allgres.pump()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER
SET search_path = argo_public, argo_private, pg_temp
AS $$ SELECT argo_public.fn_dispatch_tasks(NULL) $$;

-- Best-effort privilege drop for the runtime background worker.  It connects as
-- the bootstrap superuser (so a missing role can never crash-loop the worker at
-- startup) and calls this at the top of every transaction, so ordinary work runs
-- as `worker` instead.  Returns false when the role is not there yet.
CREATE OR REPLACE FUNCTION allgres.assume_worker_role()
RETURNS boolean
LANGUAGE plpgsql
AS $fn$
BEGIN
  EXECUTE 'SET LOCAL ROLE worker';
  RETURN true;
EXCEPTION WHEN others THEN
  RETURN false;
END;
$fn$;

CREATE OR REPLACE VIEW allgres.agents AS
SELECT a.agent_id, a.name, a.is_active, a.created_at, a.updated_at
FROM argo_private.agents a;

CREATE OR REPLACE VIEW allgres.tasks AS
SELECT task_id, session_id, agent_id, parent_task_id, status, step_count,
       input, output, error, created_at, updated_at
FROM argo_private.tasks;

REVOKE ALL ON SCHEMA allgres FROM PUBLIC;
GRANT USAGE ON SCHEMA allgres TO operator, worker;
GRANT SELECT ON allgres.agents, allgres.tasks TO operator;
GRANT EXECUTE ON FUNCTION allgres.create_agent(text) TO operator;
GRANT EXECUTE ON FUNCTION allgres.create_session(uuid, text) TO operator;
GRANT EXECUTE ON FUNCTION allgres.pump() TO worker, operator;
GRANT EXECUTE ON FUNCTION allgres.assume_worker_role() TO worker, operator;

-- One PL/pgSQL RPC surface keeps HTTP routing and native code thin.
CREATE OR REPLACE FUNCTION allgres.dashboard_rpc(p_request jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = argo_private, argo_public, allgres, pg_catalog, pg_temp
AS $fn$
DECLARE
  v_action text := COALESCE(p_request->>'action', '');
  v_id uuid;
BEGIN
  CASE v_action
    WHEN 'overview' THEN
      RETURN jsonb_build_object(
        'ok', true,
        'server_time', now(),
        'version', '0.2.0',
        'agents', (SELECT count(*) FROM argo_private.agents),
        'active_agents', (SELECT count(*) FROM argo_private.agents WHERE is_active),
        'running_tasks', (SELECT count(*) FROM argo_private.tasks WHERE status IN ('queued','running','waiting_human')),
        'queued_outbound', (SELECT count(*) FROM argo_private.outbound_calls WHERE status = 'queued'),
        'failed_tasks', (SELECT count(*) FROM argo_private.tasks WHERE status = 'failed'),
        'sessions', (SELECT count(*) FROM argo_private.sessions),
        'secret_storage', argo_private.secret_storage_mode(),
        'workers', COALESCE((
          SELECT jsonb_agg(jsonb_build_object('name', backend_type, 'pid', pid) ORDER BY backend_type)
          FROM pg_stat_activity
          WHERE backend_type IN ('allgres runtime','allgres web')
        ), '[]'::jsonb),
        'recent_tasks', COALESCE((
          SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at DESC)
          FROM (
            SELECT t.task_id, a.name AS agent, t.status, t.step_count,
                   s.goal, t.error, t.created_at, t.updated_at
            FROM argo_private.tasks t
            JOIN argo_private.agents a USING (agent_id)
            JOIN argo_private.sessions s USING (session_id)
            ORDER BY t.updated_at DESC LIMIT 8
          ) q
        ), '[]'::jsonb)
      );

    WHEN 'agents.list' THEN
      RETURN jsonb_build_object('ok', true, 'agents', COALESCE((
        SELECT jsonb_agg(
          jsonb_build_object(
            'agent_id', a.agent_id,
            'name', a.name,
            'is_active', a.is_active,
            'created_at', a.created_at,
            'updated_at', a.updated_at,
            'system_prompt', p.system_prompt,
            'max_steps', p.max_steps,
            'max_retries', p.max_retries,
            'llm_config', p.llm_config,
            'permissions', COALESCE((
              SELECT jsonb_agg(jsonb_build_object('type', x.resource_type, 'ref', x.resource_ref)
                     ORDER BY x.resource_type, x.resource_ref)
              FROM argo_private.permissions x WHERE x.agent_id = a.agent_id
            ), '[]'::jsonb)
          ) ORDER BY a.name
        )
        FROM argo_private.agents a
        JOIN argo_private.policies p USING (agent_id)
      ), '[]'::jsonb));

    WHEN 'agents.create' THEN
      RETURN argo_public.fn_create_agent(p_request->>'name', p_request->>'system_prompt');

    WHEN 'agents.update' THEN
      v_id := (p_request->>'agent_id')::uuid;
      IF p_request ? 'is_active' THEN
        PERFORM argo_public.fn_set_agent_active(v_id, (p_request->>'is_active')::boolean);
      END IF;
      PERFORM argo_public.fn_set_policy(
        v_id,
        NULLIF(p_request->>'system_prompt',''),
        CASE WHEN p_request ? 'max_steps'   THEN (p_request->>'max_steps')::int    ELSE NULL END,
        CASE WHEN p_request ? 'max_retries' THEN (p_request->>'max_retries')::int  ELSE NULL END,
        CASE WHEN p_request ? 'llm_config'  THEN p_request->'llm_config'           ELSE NULL END
      );
      RETURN jsonb_build_object('ok', true, 'agent_id', v_id);

    WHEN 'run' THEN
      RETURN argo_public.fn_create_session((p_request->>'agent_id')::uuid, p_request->>'goal');

    WHEN 'tasks.list' THEN
      RETURN jsonb_build_object('ok', true, 'tasks', COALESCE((
        SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at DESC)
        FROM (
          SELECT t.task_id, t.session_id, t.parent_task_id, a.agent_id, a.name AS agent,
                 t.status, t.step_count, s.goal, s.final_answer,
                 t.output, t.error, t.created_at, t.updated_at
          FROM argo_private.tasks t
          JOIN argo_private.agents a USING (agent_id)
          JOIN argo_private.sessions s USING (session_id)
          ORDER BY t.updated_at DESC
          LIMIT LEAST(GREATEST(COALESCE((p_request->>'limit')::int, 100), 1), 500)
        ) q
      ), '[]'::jsonb));

    WHEN 'logs.list' THEN
      RETURN jsonb_build_object('ok', true, 'logs', COALESCE((
        SELECT jsonb_agg(to_jsonb(q) ORDER BY q.created_at DESC)
        FROM (
          SELECT l.log_id, l.task_id, l.step_number, l.role, l.content, l.created_at,
                 a.name AS agent
          FROM argo_private.execution_logs l
          JOIN argo_private.tasks t USING (task_id)
          JOIN argo_private.agents a USING (agent_id)
          ORDER BY l.created_at DESC
          LIMIT LEAST(GREATEST(COALESCE((p_request->>'limit')::int, 150), 1), 1000)
        ) q
      ), '[]'::jsonb));

    WHEN 'settings.get' THEN
      RETURN jsonb_build_object(
        'ok', true,
        'secret_storage', argo_private.secret_storage_mode(),
        'providers', COALESCE((
          SELECT jsonb_agg(jsonb_build_object(
            'provider_id', p.provider_id,
            'name', p.name,
            'kind', p.kind,
            'base_url', p.base_url,
            'is_enabled', p.is_enabled,
            'allow_private_network', p.allow_private_network,
            'has_secret', EXISTS (
              SELECT 1 FROM argo_private.llm_secrets s
              WHERE s.provider_id = p.provider_id AND (
                NULLIF(s.api_key,'') IS NOT NULL
                OR NULLIF(s.access_token,'') IS NOT NULL
                OR NULLIF(s.oauth_client_secret,'') IS NOT NULL
              )
            )
          ) ORDER BY p.name)
          FROM argo_private.llm_providers p
        ), '[]'::jsonb)
      );

    WHEN 'provider.update' THEN
      v_id := (p_request->>'provider_id')::uuid;
      PERFORM argo_public.fn_set_provider(
        v_id,
        NULLIF(p_request->>'base_url',''),
        CASE WHEN p_request ? 'is_enabled' THEN (p_request->>'is_enabled')::boolean ELSE NULL END,
        CASE WHEN p_request ? 'allow_private_network'
             THEN (p_request->>'allow_private_network')::boolean ELSE NULL END,
        NULL, NULL, NULL, NULL
      );
      IF NULLIF(p_request->>'api_key','') IS NOT NULL THEN
        PERFORM argo_public.fn_set_provider_secret(v_id, p_request->>'api_key');
      END IF;
      RETURN jsonb_build_object('ok', true, 'provider_id', v_id);

    WHEN 'events' THEN
      RETURN jsonb_build_object(
        'ok', true,
        'server_time', now(),
        'tasks', COALESCE((
          SELECT jsonb_agg(to_jsonb(q) ORDER BY q.updated_at DESC)
          FROM (
            SELECT t.task_id, a.name AS agent, t.status, t.step_count, t.updated_at,
                   left(COALESCE(t.error,''), 240) AS error
            FROM argo_private.tasks t JOIN argo_private.agents a USING (agent_id)
            ORDER BY t.updated_at DESC LIMIT 12
          ) q
        ), '[]'::jsonb),
        'logs', COALESCE((
          SELECT jsonb_agg(to_jsonb(q) ORDER BY q.created_at DESC)
          FROM (
            SELECT l.log_id, l.task_id, l.step_number, l.role, l.content, l.created_at
            FROM argo_private.execution_logs l
            ORDER BY l.created_at DESC LIMIT 15
          ) q
        ), '[]'::jsonb)
      );

    WHEN 'selftest' THEN
      RETURN argo_public.fn_selftest();

    ELSE
      RETURN jsonb_build_object('ok', false, 'error', 'unknown_action', 'action', v_action);
  END CASE;
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM, 'sqlstate', SQLSTATE);
END;
$fn$;

REVOKE ALL ON FUNCTION allgres.dashboard_rpc(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION allgres.dashboard_rpc(jsonb) TO operator, worker;

-- analyze_sql only parses, but there is no reason for the sandbox to reach it.
REVOKE ALL ON FUNCTION allgres.analyze_sql(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION allgres.analyze_sql(text) TO operator, worker;
